### ISSUE TITLE
How to create an application

### ISSUE THREAD

**Issue by hareemm** [USAJOBS/Help#108]
Typo: "5. Selecty Apply Online" (should read: Select)

For numbers 6-10, reevaluate capitalization. If they are buttons/labels, they should also be bolded, as they are in every other page. Ideally these should also be (visually) sub-categorized under the last step (5), since they are sub-steps.

@humancompanion is this a bug or an enhancement? (see below)

Under "Related Articles" - remove "How to create an application"

<img width="327" alt="screen shot 2016-08-11 at 10 39 35 am" src="https://cloud.githubusercontent.com/assets/17989522/17592536/b004c90c-5fb0-11e6-80b4-e0fa699ddd00.png">

**Comment by dalenard21** [comment]
@hareemm - I fixed the typo.  another good catch.

Regarding the sub-steps, I bolded them and you're correct, they should appear as sub-steps under step 5.  But for some reason, it's not rendering correctly.  @humancompanion can you take a look at the page in github to make sure I did it right so they appear as sub-steps?

The Related Articles issue is a bug I think - @humancompanion can you confirm?  I can add a separate git issue for all related articles.

**Comment by humancompanion** [comment]
It wasn't clear if the sub-steps should retain their numbers or be an unordered list. The latter could be done with markdown but the former, which is what I opted for, required converting this list to HTML. Reopen this if it isn't what you are looking for.
