### ISSUE TITLE
How to update an application

### ISSUE THREAD

**Issue by hareemm** [USAJOBS/Help#111]
"Review" in step 7 should be bolded.

Under "Related Articles" - remove "How to update an application".

<img width="348" alt="screen shot 2016-08-11 at 11 07 45 am" src="https://cloud.githubusercontent.com/assets/17989522/17593439/dc988208-5fb3-11e6-84c4-0741ef86b8d5.png">

**Comment by dalenard21** [comment]
@hareemm 

I fixed the "bold" in step 7.

Regarding the related articles list - this is an issue on several pages.  I added a new issue to track it and assigned to @humancompanion 

See #120 

Closing this issue.
