### ISSUE TITLE
How to save an application

### ISSUE THREAD

**Issue by hareemm** [USAJOBS/Help#112]
This "You can view your saved application in your USAJOBS account." should read "You can view your saved application in your USAJOBS account:" 

Under "Related Articles" - remove "How to save an application"

<img width="339" alt="screen shot 2016-08-11 at 11 51 17 am" src="https://cloud.githubusercontent.com/assets/17989522/17595170/ee8bcb40-5fb9-11e6-9cc3-3286ac78dba7.png">

**Comment by dalenard21** [comment]
@hareemm - I fixed the typos. 

For related articles issue, see git issue #120 

Closing this issue.
