### ISSUE TITLE
How to understand the job announcement

### ISSUE THREAD

**Issue by hareemm** [USAJOBS/Help#113]
Inconsistent capitalization: both sentence and title case are used for two different headers here. Standardize to sentence case.

<img width="612" alt="screen shot 2016-08-10 at 2 50 34 pm" src="https://cloud.githubusercontent.com/assets/17989522/17596065/b57488a2-5fbd-11e6-963b-07345a9efe3a.png">

also inconsistent capitalization here: 
![image](https://cloud.githubusercontent.com/assets/17989522/17596041/9adb444a-5fbd-11e6-94df-7de6ba2027de.png)

Inconsistent bolding: If "how to apply" is bolded, "qualifications" should be bolded too. And if "how to apply" is bolded once, it should be bolded from there on out:

<img width="653" alt="screen shot 2016-08-10 at 2 55 16 pm" src="https://cloud.githubusercontent.com/assets/17989522/17596101/ed7334e2-5fbd-11e6-87d7-0e4e694c8238.png">

**Comment by dalenard21** [comment]
Updated the headings to use sentence case.  Also bolded the terms in the body content.  Issue closed.
