### ISSUE TITLE
How to save a search

### ISSUE THREAD

**Issue by hareemm** [USAJOBS/Help#114]
"You can create and save up to 10 saved searches - saved searches will expire one year after yo ou create it."
 - [x] change "it" to "them"

Underline the link in "search filters".

"Click Renew Search for 1 Year to renew your search for an additional year.." 
- [x] Remove extra period.

"For example, you may want to search for all Program Analyst jobs in Washington, D.C. and another search for all Program analyst jobs in Florida." 
- [x] Fix inconsistent capitalization for "Program analyst".

Under "Create a new saved search"... 
- [ ] Fix inconsistent capitalization for "saved search"

**Comment by dalenard21** [comment]
@hareemm 

Thanks for the catches.  I fixed everything, except the underlining of the link. I think this is design system issue. I'll enter a new bug for Matt to look into.  I believe Julie found a similar bug on another page.

I also did not fix the capitalization for saved searches.  When we refer to a link, button or site 'section' (such as the tab Saved Search) we keep the same capitalization.   Referencing your saved searches in content can be lowercase, but when talking about the "section" of the site, such as "Go to your Saved Searches", we keep the same capitalization.  

I'm going to close this issue.
