### ISSUE TITLE
Help Center Testing : How to filter results by who may apply

### ISSUE THREAD

**Issue by Piglady64** [USAJOBS/Help#118]
1) All of the links below the "Federal Employees" paragraph are not underlined like the ones above the paragraph. They are underlined in GitHub.

2) UAT: Under Additional Resources (OPM) is missing

Office of Personnel Management: Hiring Authorities (UAT)

Office of Personnel Management: Hiring Authorities (OPM) (GitHub)

3) UAT: Under Additional Resources (FedsHireVets) is missing

Veterans Employment Opportunities Act (VEOA) (UAT)
Veterans Employment Opportunities Act - VEOA (FedsHireVets) (GitHub)

**Comment by Piglady64** [comment]
1) UAT: Under Additional Resources (OPM) is missing

**Office of Personnel Management: Hiring Authorities (UAT)**

**Office of Personnel Management: Hiring Authorities (OPM) (GitHub)**

2) UAT: Under Additional Resources (FedsHireVets) is missing

**Veterans Employment Opportunities Act (VEOA) (UAT)**
 **Veterans Employment Opportunities Act - VEOA (FedsHireVets) (GitHub)**

**Comment by dalenard21** [comment]
@Piglady64 

I looked in github, and the links are correct - they include the (OPM) and (FedsHireVets).  So, I guess UAT just hasn't been updated with the most recent change.

Regarding the underlining of links, I'm going to enter that as a separate git issue because it's happening on other pages.

**Comment by dalenard21** [comment]
Closing this issue.
