### ISSUE TITLE
5.8 - 20th anniversary timeline

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#122]
This issue tracks creating the 20th anniversary timeline page.

**Comment by humancompanion** [comment]
The timeline requires that all parent elements have ```height: 100%``` set on it in CSS. However, setting the ```.usajobs-help-center``` div to height: 100% across the site breaks at least the about page and possibly others. Any class I add to that parent div will be ignored when deployed because of the way we consume the site into the database. Same goes for an inline style: it would be ignored when the site is deployed.

I need to ask Saleim to copy any classes that exist on that parent div onto the wrapping parent div in his script. He may in fact have already done this for another problem we had, but without it the timeline isn't going to format correctly.

**Comment by humancompanion** [comment]
From @skpark19:

@humancompanion @hareemm Peter and I met and identified that the navigation should start with the initial introduction slide in order to communicate how the user should interact with the story. Please also explore having the timeline line visual going into the last slide as well. 

The Apple (logo) on slide 6 (on the computer) needs to be removed. Branding has been flagged in the past by the Office of Communications.

**Comment by humancompanion** [comment]
From @skpark19  - 

A few questions/notes/revisions (please let me know if you need me to elaborate on anything):

1.       Can we move titles into the same line w/ the year/range? Or should we remove the “titles”?
2.       The data is currently lost at the bottom of the page.

1996-2001

Revised summary: USAJOBS evolved with the advent of technology.

2002-2010

Revised first paragraph: The job search and resume builder were improved, and the Information Center and Veteran Resource Center added to provide additional help to the user.

2011-2013

Revised summary: USAJOBS continued to develop through innovative changes and advancements.

Peter and I looked over the design and wanted to get your thoughts on the space that removing the titles would add and how that would impact the content. I’m happy to come down to discuss this, just let me know when/if you want to touch base on this.

**Comment by humancompanion** [comment]
@skpark19 & @PeterToohey - "evolved with the advent of technology" is both grandiose and misleading. Technology existed before 1996. How about "USAJOBS evolves with the web"?

**Comment by PeterToohey** [comment]
That works for me

Sent from my iPhone

On Aug 24, 2016, at 8:43 AM, Matthew Dingee <notifications@github.com<mailto:notifications@github.com>> wrote:


@skpark19<https://github.com/skpark19> & @PeterToohey<https://github.com/PeterToohey> - "evolved with the advent of technology" is both grandiose and misleading. Technology existed before 1996. How about "USAJOBS evolves with the web"?

-

**Comment by skpark19** [comment]
That works for me as well.

**Comment by humancompanion** [comment]
Last minute feedback:

·         1996 – usajobs should be changed to USAJOBS
·         2010-2011 – The facelift image provided is incorrect, it was changed to what it is in production today (with possible minor changes)
·         2011-2013 – Average daily visits and average daily jobs should be removed
·         2014 – Average daily visits and average daily jobs should be removed
·         2015 – Average daily visits and average daily jobs should be removed
·         2016 – Average daily jobs should be added, but not average daily visits

**Comment by humancompanion** [comment]
Previous feedback from @skpark19 that hasn't yet been addressed:

> Can we narrow the distance between the title and the summary, and then move the year down. From  2011 on the line with the circle showing navigation becomes a bit cramped. 
>  
> It is challenging to see/read the data from 2011-13 on.
>  
> I will defer to you on this but in the example we based this on the lines go through the page, I know we designed it differently and now there is text rather than an image but is there on a way to connect everything a bit more (slide to slide)?

**Comment by humancompanion** [comment]
From @gkerster :

```
Trend Year          Trend Month     Average Daily Open Jobs
2015                       7                              14385
2015                       8                              14734
2015                       9                              14223
2015                       10                           13530
2015                       11                           13607
2015                       12                           13547
2016                       1                              12746
2016                       2                              14576
2016                       3                              15163
2016                       4                              14856
2016                       5                              14609
2016                       6                              14030
2016                       7                              14209
```

**Comment by skpark19** [comment]
@humancompanion additional feedback:

1. Line/Circle visual for navigation:
a. Intro slide, the navigation isn't showing up until you scroll. Extend circle and line further into the initial slide.
b. Final slide, the navigation visual isn't continued into this slide
2. 2010-2011, monitor needed
3. Top navigation is lost after the first slide, users have to scroll back to the top in order to sign in, search, etc. Is there a way for us to orient users as they navigate through the timeline?
a. Katrina recommended a footer
4. A comment I have heard multiple times is that the first and last slides feel like after thoughts as they are the only slides that do not have images. Something to discuss.

**Comment by humancompanion** [comment]
* [ ] Add anniversary star to opening slide. 
* [ ] Alter color on opening slide.
* [ ] Break out "scroll down to explore"
* [ ] Add top shade pull on last slide.
* [ ] Add image to last slide.
* [ ] Add back to top or home page on last slide.
