### ISSUE TITLE
Related articles header should not appear when list is empty

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#126]
On the Which web browsers work faq: http://usajobs.github.io/Help/faq/troubleshoot/

The Related Articles right side nav appears with no articles beneath.  Likely because this is the only page in this section.  But, it should show if there are no related articles.

**Comment by dalenard21** [comment]
This is also happening on the how to search by map page: http://usajobs.github.io/Help/how-to/search/map/

**Comment by humancompanion** [comment]
I tried to fix this again this evening and Jekyll/Liquid are just not co-operating. Given all the other things on my plate this will have to wait a bit until I can try again and determine how to debug.
