### ISSUE TITLE
Add top 5 answers

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#131]
We now have the top 5 questions asked from the Help Desk. Next step is to ensure we have how-to articles that address all 5.

* [ ] How do I change my password?
* [ ] What should I do if I no longer have access to the email associated with my USAJOBS account?
* [ ] Why did USAJOBS rate my application as not qualified?
* [ ] How do I change my password when I don't remember my three security questions?
* [ ] Where is my application status?

**Comment by humancompanion** [comment]
@dalenard21, @Piglady64, & @PeterToohey: I stubbed out these pages last night and revised the home page. I might tweak the home page further based on analytics to highlight the most popular articles throughout the FAQs, How to, and Working in Government sections on the home page. However, it would be great if you three could take the lead on ensuring the top 5 articles are tightened up and reflect the correct information. Thanks!

**Comment by dalenard21** [comment]
Will this be for 5.9?

**Comment by PeterToohey** [comment]
Yeah

Sent from my iPhone

On Aug 18, 2016, at 1:44 PM, dalenard21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Will this be for 5.9?

-

**Comment by dalenard21** [comment]
Per @humancompanion email, looks like we need a page for How do I contact USAJOBS as well.

Here are the pages we need to create and/or revise based on feedback from the help desk.

**New Pages**

- [ ] What should I do if I no longer have access to the email associated with my USAJOBS account?

- [ ] How do I change my password when I don't remember my three security questions?

- [ ] Why did USAJOBS rate my application as not qualified? (this is similar to Why was I not considered for a position? faq - revise or add a new page?)

- [ ] How do I contact USAJOBS?


**Revise existing pages (as needed)**

- [ ] How to change a password

- [ ] Where is my application status (perhaps rephrase the How to check on application status)

- [ ] How to reset a password (pull out the content about security questions and email to put those on new pages - link to these pages from reset password)

@PeterToohey , @humancompanion 

What is the message/steps we want to convey for the "How do I contact USAJOBS" question?

**Comment by humancompanion** [comment]
@dalenard21 - I stubbed out some content for the how do I contact page:

http://usajobs.github.io/Help/how-to/contact-usajobs/

However, it did not perform well in usability testing. Users wanted to contact us from this page (surprise!) and after reading the content still didn't find the right way to contact us. My plan at the moment is to change the "Still need help?" treatment to just "Contact Us".

**Comment by dalenard21** [comment]
Add to this list: How to remove a saved job.

@humancompanion and I updated the content on How to manage documents, but it may make more sense to call this out on it's own page.

### @humancompanion - what about this approach?

1. Create new page: How to remove a saved job from your saved jobs list?  (or something like that).

Suggested copy:

To remove a saved job:

1. Go to your Saved Jobs.
2. Click the job title or **+** to expand the job details.
3. Click **Saved**.
4. Go to a different page and come back to your **Saved Jobs**--this will refresh the page and you will no longer see the job in your list.

2. Edit the copy on "How to save a job" to this:

**Apply, view more or remove saved jobs**
Within the saved jobs details you can also apply, remove, or view more similar jobs.

The "remove" will link to the new "How to remove a saved job" page.

Thoughts?

**Comment by dalenard21** [comment]
Sent all content edits to Tracy on Monday, with exception of How to remove a saved job - I sent that content today.

**Comment by dalenard21** [comment]
@humancompanion, @petertoohey

The "top 5" questions we sent to the help desk and the answers they provided back don't match up.  The help desk changed some of the questions.  Weird.  I did my best to go through their answers and either edit or create new content based on top questions from users.  The following pages have been updated or created:

- [ ] How to reset password - https://github.com/USAJOBS/Help/blob/master/how-to/account/password/reset.md - edits based on help desk feedback and reviewed by Tracy.

- [ ] How to reset your password when you've forgotten your security questions -https://github.com/USAJOBS/Help/blob/master/how-to/account/password/forgotten-security-questions.md - new page 

- [ ] How can I access my account when the email address on my account is no longer valid -https://github.com/USAJOBS/Help/blob/master/how-to/account/access.md - new page

- [ ] How to see your application status - https://github.com/USAJOBS/Help/blob/master/how-to/application/status.md - edits to existing page, but changed page title 

- [ ] How to remove a saved job - https://github.com/USAJOBS/Help/blob/master/how-to/job-announcement/remove.md - new page

- [ ] How to save a job - https://github.com/USAJOBS/Help/blob/master/how-to/job-announcement/save.md - edits to existing page - added link to how to remove a saved job

- [ ] How to contact USAJOBS - https://github.com/USAJOBS/Help/blob/master/how-to/contact-usajobs.md - new page

- [ ] Why was my application not qualified? - https://github.com/USAJOBS/Help/blob/master/faq/application/not-considered.md - edits to existing page, changed page title to match what's coming into help desk

 I did not make any changes to how to change a password.  Even though that was a "top question" the help desk sent back the answer for how to reset a password.  It's not the same. I think we keep how to change a password and how to reset a password.  If it still causes confusion we can combine into one.

Let me know if I missed any other content.

**Comment by dalenard21** [comment]
Oops.  one more - I updated the How to save a search page to add more info about email notifications and make sure the steps match what's in production (Save This Search vs. Save Current Search).

- [ ] How to save a search

**Comment by humancompanion** [comment]
@dalenard21 - I like your idea RE: #issuecomment-243566897. Glad to see you made it so (I fixed the link from the save page to the remove page). Also, agree on the keeping of how to change a password. We should raise that issue with the help desk. @PeterToohey - Can you follow up with them?

These changes all made it into the final build of 5.8 so thanks for taking care of these so quickly!

**Comment by PeterToohey** [comment]
@humancompanion @dalenard21 To be clear, we want to follow up with the helpdesk about why they mixed up reset vs change password?  Also, whether they see the need to two separate help pages?
