### ISSUE TITLE
Update saved jobs new limit

### ISSUE THREAD

**Issue by kyhryt** [USAJOBS/Help#135]
You can save up to 25 job announcements in your USAJOBS account.

https://www.usajobs.gov/Help/how-to/job-announcement/save/

**Comment by humancompanion** [comment]
@nourax - Can you confirm that this is what dev has coded: Saved jobs limit = 25? @kyhryt was able to add more than 10, but I'm not sure he tried to add 26 to see if that is in fact the new limit. (Ky - If I'm wrong about that just update this issue. Thanks.).

**Comment by humancompanion** [comment]
Ky has confirmed that 25 is the new limit.
