### ISSUE TITLE
Add sentiment measurement

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#146]
It would be helpful to measure how folks are feeling after reading a Help Center article. I like this treatment: https://beta.fec.gov/data/ (noticed it while looking at their use 18F's glossary). Not sure if we should measure:
#### Sentiment

After reading this article describe how you feel:
- Happy
- Sad
- Angry
#### Task completion

Do you feel you will be able to complete your intended task after reading this article?
- Yes
- No
- Maybe

Or something else entirely.

**Comment by humancompanion** [comment]
@hareemm and @Piglady64 please work on this together. I'm not sure when I'll have a chance to implement what you come up with, but I would like to make progress on the design. We could potentially A/B test this in production though it wouldn't be randomized (i.e. we could pick which articles get which treatment and they'd stay that way for some period of time). Might be worth it. Feel free to conduct an informal or formal test as long as it doesn't get in the way of upcoming search tests.

**Comment by dalenard21** [comment]
@Piglady64 It's been 2 years. Do we want to pursue this or close?

**Comment by dalenard21** [comment]
Closing this issue.
