### ISSUE TITLE
how-to/account/profile steps are no longer accurate

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#149]
This is actually a bug from 5.7. We failed to update the create a profile page to reflect the new sections.

**Comment by dalenard21** [comment]
@humancompanion, I'll update the content.

**Comment by dalenard21** [comment]
@humancompanion 

Looks like the only change needed is changing "Other" to "Preferences".  I made that change.  I think the rest is okay, but let me know if there's anything else that needs to be updated.
