### ISSUE TITLE
how-to/account/access/ contact us form is exposed and broken

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#151]
The contact us form is prematurely available and when submitted is broken because it doesn't have the changes in the 5.9 branch. This is a remnant of the test we performed. The fix is to change the layout back to article.

**Comment by humancompanion** [comment]
@dalenard21 mentioned there are more pages:

"How to reset password, how to sign into your account if you don’t have access to email, etc."

I'm not finding that to be the case. Reset password has the article layout. It's just how-to/account/access/ from what I could find.

**Comment by dalenard21** [comment]
@humancompanion 

You're correct.  Those pages do not have the form exposed, BUT in the help text of a few articles, it tells the user to "scroll below and fill out the contact us form".  They were written that way for when the new form does go out and is exposed or at least the link is there.

I think it's just two pages that reference the form "below":

https://www.usajobs.gov/Help/how-to/account/password/reset/security-questions/
https://www.usajobs.gov/Help/how-to/account/password/reset/

I don't think it warrants changing the content, but just wanted to bring it up.

**Comment by humancompanion** [comment]
Ah, now I see. Given that the link to go to contact us is at the bottom I think we're okay for the short period of time we'll have 5.8 out there before 5.9 replaces it.
