### ISSUE TITLE
Provide list of system generated emails

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#154]
Provide list of system generated emails including the content, to Dan.  Update the emails to include links to specific help center pages instead of just the contact us page, since that is going away in 5.9.

**Comment by humancompanion** [comment]
I compiled all the “new” system generated emails into the attached spreadsheet. 
 
FINDINGS
1.       “Contact us” appears as a link in every email footer.  The current footer language is:
 
“To make sure you get USAJOBS emails in your inbox (and not your spam), add 'notifications@usajobs.gov' to your address book.
 
If you doubt the authenticity of a USAJOBS email, please visit https://[[site]] using your browser. From there, you can log in to your account if an activity is being requested or contact us directly to inquire about the authenticity of the email.
 
Please do not reply to this message. Replies to this message go to an unmonitored mailbox.
 
Have questions or comments? Visit our Help Center.” (there is a url for help center)
 
“contact us” links to the current contact us page.  We don’t have a page in the help center that talks about authenticity of emails from USAJOBS.  Perhaps we need one?  Not sure how else to handle. Please let me know if you have ideas.
 
2.       “Contact us” appears in a couple emails in the body text. I think we can replace with direct links into specific help center articles, i.e. “how to reset your password” and “how to change a username”
3.       A few emails use help@usajobs.gov. (i.e.Seeker Account Delete Final). Is this email address where the contact us form goes?  Should we remove the direct email link?
 
I can work on editing all of the emails – it’s not that many, and the footer would be a one-time thing.

**Comment by humancompanion** [comment]
@dalenard21 - That's good news about #1. As for #2, the contact us form is submitted to the help desk. Not sure if that is via email or directly inserted into footprints. I'd leave that decision to Dan.

Thanks for handling the editing of the emails. Please file an issue for adding an article on the authenticity of emails from us. We can handle that in a future release.

**Comment by dalenard21** [comment]
Provided updated email footer text and individual emails to remove links to "contact us" to Dan.

There are a handful of emails that will retain the "help@usajobs.gov" email address as CTA for potential security issue (i.e., didn't change/reset your password?, didn't change your secondary email address?).  Included links to help center pages where applicable.

Issue closed.
