### ISSUE TITLE
Hiring Paths links points to old design

### ISSUE THREAD

**Issue by kyhryt** [USAJOBS/Help#156]
I was doing some digging around last night and realized a few of our hiring paths links point to the old design: 
https://www.usajobs.gov/Veterans/
https://www.usajobs.gov/StudentsAndGrads

These links show up in google search results - see attached. 

<img width="1430" alt="screen shot 2016-09-14 at 9 39 40 am" src="https://cloud.githubusercontent.com/assets/15234468/18514423/90ebfaee-7a5f-11e6-9dc9-83e5067f6fc6.png">

**Comment by humancompanion** [comment]
This is a Core bug, not a Help Center bug. @kyhryt - Please work with @kbwagner to get this ticket created in TFS. I believe those results are controlled by structured data (https://developers.google.com/custom-search/docs/structured_data), but I've not set that up myself so I'm not terribly familiar. I don't see us providing a sitemap.xml file any longer which is one way we might have provided that metadata to google. At any rate, there are ways for us to control which links are featured there. What we have selected to feature there is a little odd and should probably be revisited. 

While we are filing that bug we should also file a ticket to properly redirect those old URLs to their new location:

https://www.usajobs.gov/Veterans/ > https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/veterans/
https://www.usajobs.gov/StudentsAndGrads > https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/
et. al.
