### ISSUE TITLE
Update PeaceCorps and AmeriCorps Content Page

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/Help#158]
Through events discussions with contacts at Vista and Peace Corps they have requested to updates to their copy:

- [x] Ensure it is 'AmeriCorps" not "AmeriCorp" - based off my review there are 5 references to AmeriCorp

- [x] Change the first line from "If you worked for the Peace Corps or AmeriCorp VISTA, you may qualify for non-competitive eligibility" to "If you served with the Peace Corps or AmeriCorps VISTA…"

**Comment by humancompanion** [comment]
I think I only found 4 references. Can you confirm I've fixed this and close this bug if I have? Thanks.

http://usajobs.github.io/Help/working-in-government/unique-hiring-paths/peace-corps/

**Comment by dalenard21** [comment]
@humancompanion - Looks like the references to Americorps has been fixed.

But the first sentence in the "hero" still needs to be updated to ""If you served with the Peace Corps or AmeriCorps VISTA…" instead of "If you worked for..."
