### ISSUE TITLE
Create FAQ for usajob email authenticity

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#160]
Need to create an FAQ that talks about USAJOBS email authenticity -- this is referenced in the footer of all emails sent to users and we have nothing on the site that explains what that means.

Also, this is a good way to drive users to this page, where they then could submit a contact us form.

**Comment by dalenard21** [comment]
@humancompanion 

Per Dan and Leon, we are okay to remove this language from the automated email footer:

 "From there, you can log in to your account if an activity is being requested or contact us directly to inquire about the authenticity of the email. ". 

Do you think we still need a page that talks about email authenticity?

**Comment by humancompanion** [comment]
Well, what would the contents say? Sounds like it isn't a hot topic, but it wouldn't hurt to cover it either IF (and only if) there is a easy for users to verify the authenticity of our lovely text emails.

**Comment by humancompanion** [comment]
I like the content of this page:
https://www.paypal.com/us/selfhelp/article/how-to-spot-fake-emails-faq2340

Given that this came up during login.gov usability testing it would be good to mention something. I know we got permission to remove the text, but I'd like to find a path forward that is simple for users that want to verify the authenticity of an email.

If we decide to go with the FAQ I think it should contain:
* What types of emails we send (job search results, account management, etc.)
* What types of emails we do not send (sign in and give us your soc. sec. #)
* Perhaps an explanation and sad admission that some of our emails will come as text and some as responsive HTML?

**Comment by dalenard21** [comment]
@humancompanion did a little research and found similar information on the following sites:

**Target Red Card** - they have quite a bit of info, likely given their breaches in the past.
https://rcam.target.com/help/HelpOAMSecurity.aspx
https://www.target.com/c/benefits-identity-safeguards/-/N-4srzk#lnk=REDcardidentity

**LinkedIn** - they also have lots of info on security
https://www.linkedin.com/help/linkedin/answer/62920?src=li-other&veh=www.linkedin.com%7Cli-other
https://www.linkedin.com/help/linkedin/answer/62918
https://www.linkedin.com/help/linkedin/answer/5342

I think these bullets might be the type of info we'd want to use:
* We include your full first and last name, as well as your current professional headline, in the footer of all our messages to help you identify legitimate LinkedIn communications. Discard any messages claiming to be from LinkedIn but don't have our security footer.
* Our messages will never ask you to download software or provide sensitive information such as a password or a Social Security Number.

**Capital One Bank** - I'm guessing most bank sites will have info about security.  Capital One doesn't specifically call out how to identify their emails, but does provide guidance on how to detect phishing emails.  Plus, lots of other identify/security info.
https://www.capitalone.com/identity-protection/commitment/

**Monster** - has a 'security center'
http://inside.monster.com/security-center/home.aspx

There are enough examples of sites putting out info to help users protect themselves.  If we can find out how we address our users and the type of information we do and DO NOT collect via email, I think we can create a page that's not 'doomsday', but helpful enough to users so they know they can trust an email.  OR we have them call the help desk if they're not sure.

**Comment by humancompanion** [comment]
@dalenard21 - I stubbed out the file here so you can start creating it:
http://usajobs.github.io/Help/faq/emails/
