### ISSUE TITLE
Create how-to for contacting us regarding account activation trouble

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#162]
We need a page that acts as a specific target from the "Activate your account" page:
http://usajobs.github.io/design-system/account/success/

The page that the "Contact us" link points to should have the contact us form expanded by default and should probably be the long version of the form.

Please track down what the help desk currently does in this situation (have user check their spam folder, what else?) and write appropriate content. Once the content is in this issue I can create the page.

**Comment by Piglady64** [comment]
I couldn't find anything about this in the quick responses in footprints so I sent an email to Karen Defore to find out what they send to the user. I also cc'd Hareem so if Karen responds while I am on vacation she will get the information too. Dan said he thought Karen was back from her detail. We will see

**Comment by humancompanion** [comment]
@Piglady64 - Can you pick this up again? Thanks.

**Comment by humancompanion** [comment]
This is superseded by the login.gov work.
