### ISSUE TITLE
List of hiring paths is incomplete on Help/faq/application/eligibility/

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#177]
Update the list under item 2 to match the hiring paths featured throughout the site. Alternatively, link to the index page for hiring paths.

**Comment by humancompanion** [comment]
@dalenard21 - This page needs a bit of a revamp I suspect given our updated understanding of eligibility. Use of "status" here is a bit misleading as status is really only relevant to reinstatement. We drew a diagram on the white board yesterday that may overlap with https://trello.com/c/xMa4XMuq/808-create-visualizations-to-explain-levels-of-service-and-appointment-types.  But it helped Hareem and others understand the break down of competitive service.

Also, this may be a router page where we just redirect to other parts of the site. It feels like this is repeating what we have elsewhere in greater detail.

**Comment by dalenard21** [comment]
Add all of the hiring path links to this page.

We do need to update all of this content but we can do that post April 8.

**Comment by dalenard21** [comment]
closing this issue because the hiring path links now match what will be on the site April 8. Will open a new issue to address the rest of the content on this page
