### ISSUE TITLE
Revise how to filter by location to include autocomplete details

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#182]
We have the page how to filter by location - we don't need two pages.  This page should redirect to the how to filter by location page.

https://www.uat.usajobs.gov/Help/how-to/search/location/

should now direct traffic to:

https://www.uat.usajobs.gov/Help/how-to/search/filters/location/

**Comment by humancompanion** [comment]
Hmm. I had thought we'd keep them separate but now I see that filtering by location covers searching as well. However, the filter page doesn't cover everything that can be found via autocomplete:

* city
* state
* country
* county
* postal code

It should probably mention those given that we don't anywhere else. I will remove the how-to/search/location page.

**Comment by dalenard21** [comment]
The content does already talk about city, state, zip code and country.  I added county.  The step by step does mention auto-populated choices, which I think covers autocomplete. @humancompanion  let me know if you think there needs to be more.

closing issue.
