### ISSUE TITLE
How to understand search results doesn't mention grade

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#186]
@dpboyd raised the issue of how-to/search/results/ not mentioning grade. We need to add grade. Use this for reference http://usajobs.github.io/design-system/search/#results

**Comment by dalenard21** [comment]
added "grade" to the paragraph about salaries.  It actually did talk about GS pay scale/grade, but the heading didn't include grade.  Added "grade" to the sub-heading.  It already links to how to filter by pay, which includes more details on pay grade.

closing issue.
