### ISSUE TITLE
Nav - Missing search icon and misalignment plus background image misalignment

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#194]
From @dpboyd, 2 bugs:

![image](https://cloud.githubusercontent.com/assets/352987/24527160/fe7615d6-156e-11e7-8d06-6c1082fe1dfc.png)

I'm not able to reproduce in the iOS simulator nor in Chrome at that width. The background image issue is odd as the styling sticks to standard directives:

```
usajobs-help-center-search-banner, 
.usajobs-help-center-search-banner--with-nav, 
.usajobs-help-center-title-banner {
  padding-top: 1.5rem;
  background: #112e51;
  background-image: url(../img/help-center/helpcenter_star.png);
  background-image: url(../img/help-center/helpcenter_star.svg);
  background-position: right top;
  background-repeat: no-repeat;
}
```

The missing icon on Windows Phone is interesting. I have one at home I can use. I'll check on it tomorrow.

**Comment by humancompanion** [comment]
I tracked down the IE background issue: It won't position an svg. At all. Thus I've added CSS to try and mitigate that. 

Still looking into the missing icon on Windows Phone.

**Comment by humancompanion** [comment]
My fix didn't work for the IE background because it is not identifying itself as IE via modernizr. Interesting.

**Comment by humancompanion** [comment]
This is happening in production now and I'll have to use a CSS hack to detect IE10 and up to address this. I will do that post-search deployment.

**Comment by dalenard21** [comment]
This appears to be fixed on my iPhone and Alex's Android.
