### ISSUE TITLE
Update National Guard UHP with content edits

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#197]
Matt,

You may have already grabbed these edits for National Guard, but here's the word document with edits in RED.

This should go out with the April 8 release
[UHP-National-Guard_220170313.docx](https://github.com/USAJOBS/Help/files/886324/UHP-National-Guard_220170313.docx)

**Comment by humancompanion** [comment]
Debbie was correct. I did grab these changes already.
