### ISSUE TITLE
UHP: Pathways - Discuss excepted service time conversion

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#208]
We should mention on this page that your time in the excepted service converts to competitive service time when you come in through the Pathways program:

https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/faq/pathways-program-employment/

**Comment by dalenard21** [comment]
@humancompanion here's a revised version.
[Help-center-faq-Do-Pathways-Programs-jobs-lead-to-permanent-employment.docx](https://github.com/USAJOBS/Help/files/918411/Help-center-faq-Do-Pathways-Programs-jobs-lead-to-permanent-employment.docx)

**Comment by humancompanion** [comment]
Looks good to me. Can you update that page with that content?

**Comment by dalenard21** [comment]
@humancompanion I updated the page.  Issue closed.
