### ISSUE TITLE
Search: Unarchived saved searches do not include hiring paths from profile

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#209]
@dpboyd mentioned that when a saved search is unarchived it will not include hiring paths. We should address that somewhere on the site. Perhaps here https://www.usajobs.gov/Help/how-to/search/save/ or perhaps a new page that discusses unarchiving explicitly?

**Comment by dalenard21** [comment]
@humancompanion is this only for saved searches that were created before April 8?

**Comment by humancompanion** [comment]
Yes. For saved searches that folks are unarchiving there are some caveats.

**Comment by dalenard21** [comment]
@humancompanion 

I think we should add an FAQ that speaks to what happened to saved searches created prior to April 8.  I've attached some content.  It doesn't talk about each filter that changed, but does talk about unarchiving and checking the search to see if there are changes and update them.

I'm open to adding content around what filters have changed, but what are your thoughts on that?

We can also link to this page from the How to save your search page.

[Help-center-faq-saved-search-april-8_20170411.docx](https://github.com/USAJOBS/Help/files/918396/Help-center-faq-saved-search-april-8_20170411.docx)
