### ISSUE TITLE
Update How to save a search

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#21]
Our how to on saving a search is inaccurate and not terribly helpful. We need step-by-step content in there. We are updating the first link on this page https://www.usajobs.gov/StudentsAndGrads/ to point to the new help center content.

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

Edited how to save a search.  I'd like one of you to review to make sure I got the steps right and the correct button language.  I looked at American Discovery Trail for examples of the search feature.

Let me know if further edits are needed.

**Comment by dalenard21** [comment]
Received feedback from @PeterToohey and included his edits.  How to Save a search is good to go. Closing issue.
