### ISSUE TITLE
Update language on How to contact us help center page

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#211]
Per feedback from Carla and help desk, update the language to better explain how to find the contact us form. Consider explaining the following points in more detail.

Try to find the answer to your question...
Look for a topic that most closely matches your question
Click on the "Contact us" button if the information doesn't answer your question
Fill out the form and click "Send"

**Comment by dalenard21** [comment]
Sent suggested edits to Tracy for review.

**Comment by humancompanion** [comment]
@dalenard21 - Can you share the edits here so that I can prepare them? I'd like to get another build to dev a.s.a.p.

**Comment by dalenard21** [comment]
@humancompanion sure, I've added the edits, but they haven't been reviewed by Tracy yet.
[Help-center-how-to-contact-USAJOBS-without-why-no-form_20170425.docx](https://github.com/USAJOBS/Help/files/958433/Help-center-how-to-contact-USAJOBS-without-why-no-form_20170425.docx)

**Comment by dalenard21** [comment]
@humancompanion - Tracy reviewed and approved the how to contact us updates.  Here's the final content to use 
[Help-center-how-to-contact-USAJOBS-without-why-no-form_20170425.docx](https://github.com/USAJOBS/Help/files/987555/Help-center-how-to-contact-USAJOBS-without-why-no-form_20170425.docx)
