### ISSUE TITLE
Create profile preferences content

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#215]
We need to add search profile preferences content.

**Comment by dalenard21** [comment]
Tasks:

 - [ ] Update profile preferences alert messaging in search results - refer to the wiki and trello card
 - [ ] Update how to create a profile to add language about benefits of filling everything out for search
 - [ ] Add a page for how to use your profile when searching - would this go under search?

@humancompanion I don't know if we need more content about this.  You either turn it on or off in search results and then we want them to fill it out completely to get the most benefit.  let me know if you think we need to update anything else.

**Comment by humancompanion** [comment]
Content created and Help Center portion is complete.
