### ISSUE TITLE
FAQ aimed at past users of RSS

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#221]
Essentially the options are use our API or individuals set up their own saved searches.

> From: <Thibodeau>, Dan 
> Date: Monday, May 1, 2017 at 2:04 PM
> Subject: FW: [CONTENT-MANAGERS-L] USAJOBs.gov's search RSS: gone forever?
>  
> Brian’s question is answered, but I also just got off the phone with Jeffrey. He did state that they were using RSS to automate emails to users who wanted EPA and now USCIS jobs. Though after talking, he did see the benefit in having users set this up in USAJOBS so they could tailor the notifications to results that were actually relevant to them instead of all jobs at an agency, though they can set that up in their account too.
>  
>  
> From: Thibodeau, Dan 
> Sent: Monday, May 01, 2017 2:02 PM
> Subject: RE: [CONTENT-MANAGERS-L] USAJOBs.gov's search RSS: gone forever?
>  
> Hi Brian,
>  
> Just to add onto this one. If you were using the RSS feed to be notified of updates, meaning new jobs posting since that’s the only place the RSS feed was, you can set up a saved search through your USAJOBS account as well. When setting it up, you can select your notification frequency. While this of course wouldn’t be the best method for agencies as in Jeffrey’s question, it could certainly assist an individual user.
>  
> From: Brian Kim 
> Sent: Monday, May 01, 2017 1:57 PM
> Subject: Re: [CONTENT-MANAGERS-L] USAJOBs.gov's search RSS: gone forever?
>  
> I rather RSS than social media.
> 
> I always thought that RSS was the lowest cost, least intrusive, option for both provider and consumer. Isn't it just a plain web page?
> 
> Don't the modern content manager systems automate it, eg. WordPress feeds?
> 
> Personally, as a consumer, I do my own aggregation, and I like that.
> 
> Does anyone use WordPress feeds or anything similar?
> 
> "What is RSS
> 
> ... Wouldn’t it be nice if you could tell your favorite websites to let you know every time they update? Well, this is exactly what RSS does. RSS allows users to keep track of their favorite websites without having to manually visit the website each time." 
> http://www.wpbeginner.com/beginners-guide/what-is-rss-how-to-use-rss-in-wordpress/
> 
> I find RSS more appealing than mechanism likes "following" in flickr.com or "channels" in youtube.com. It's easier on my mailbox too.
> 
> Or is the difficulty training/maintaining the content submitter?
> 
> I don't get it. I have always felt RSS the most considerate way for a provider to "get my number".
> 
> 
> Happy Monday,
> Brian 
> 
> From:        "Levy, Jeffrey M" 
> Date:        05/01/2017 07:24 AM
> Subject:        [CONTENT-MANAGERS-L] USAJOBs.gov's search RSS: gone forever?
> 
> Hello to our OPM colleagues. 
>   
> You used to have a wonderful feature on usajobs.gov that let someone do a search and then create an RSS feed of that search. For several years, across two agencies, I’ve used that feed to drive multiple channels: automated daily emails with new listings, job listings on our website, and Twitter feeds. Here at USCIS, for example, the daily email has 31,000 subscribers. I seem to remember from my time at EPA that they had even more email subscribers. 
>   
> It seems that in your recent redesign, you dropped that service. I’m not here to complain; we all have to make decisions based on resource use and the benefit that results. But I did want to let you know that service was used by at least two agencies, and ask whether there’s any chance I could talk you into reinstating it? 
>   
> Thanks!

**Comment by dalenard21** [comment]
It's been 2 years and no other requests for RSS feeds. Not adding an FAQ and closing issue.
