### ISSUE TITLE
Improve ICTAP, CTAP, Reinstatement, Transfer and Interchange help content

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#226]
* [ ] CTAP/ICTAP
* [ ] Interchange Agreements
* [ ] Reinstatement

**Comment by humancompanion** [comment]
Adding comment history:

@kyhrytaylor - The reinstatement page, according to Michelle Glynn, is inaccurate. The change went into effect 8 months ago to allow any time, non-contiguous, to count towards reinstatement. I added some comments to the InVision page.

The "How long am I eligible" section doesn't make sense to me. "Less than one year" from when? It lacks context.

Interestingly, OPM's page has not changed:
https://www.opm.gov/policy-data-oversight/hiring-information/reinstatement/

The Federal Register is here: https://www.federalregister.gov/
But, I cannot find the document in question. I don't believe it was an OPM generated order but here are OPM's docs:
https://www.federalregister.gov/agencies/personnel-management-office

Can you follow up with Michelle Glynn and let her know that despite our best efforts we can't find this regulation change and we need to see it make sure we get our plain language version correct? Also, let's get clarity on "lifetime for both career and career conditional" I believe she was saying that the time limit on eligibility is gone but, let's confirm. Thanks. You could update the page and send that to her if you prefer or send an email with those questions.

**Comment by humancompanion** [comment]
I have only brief notes from the meeting:

Reinstatement
Can be reinstated right away. Up until 12/16 you needed 3 continuous years. Now all time stands alone. Regulation change. Could point to Federal register.
Now lifetime for both career and career conditional.
Transfers
Kill this page
Interchange agreement
Employees who were involuntarily separated are eligible within one year of the separation under third point.

**Comment by humancompanion** [comment]
Okay, I found Ky's files (they were in a unique hiring paths sketch file) and put them back up on InVision: https://opm.invisionapp.com/share/8MN8PMPUGEP

**Comment by dalenard21** [comment]
@humancompanion 

Here's an updated version of reinstatement. 

I can't find the content I originally wrote and gave to Ky.  I know I edited this in Invision, but probably lost those comments.

So, I have questions and probably need to go back to Michelle G.  

1. Do you still have to be a former COMPETITIVE service employee or can any former federal employee apply under reinstatement?
2. I know you no longer have to work 3 continuous years, but do you have to work at least 1 year?  Or, can ANY former employee apply under reinstatement...even if they only worked for 3 months?
3. Do you still have to leave the job voluntarily?
[Reinstatement_20180801.docx](https://github.com/USAJOBS/Help/files/2250996/Reinstatement_20180801.docx)

**Comment by dalenard21** [comment]
I sent this to Michelle G.  She's out of the office until tomorrow.
