### ISSUE TITLE
Help Center - More updates to Contact Us

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#229]
Per emails from Dan, trying one more edit to the Contact Us page to make it clear that users need to go to a different page in the Help Center to submit a form.

Content is attached.

@humancompanion let me know if I can make the updates or if you need to.
[How to contact USAJOBS-updates_20170524.docx](https://github.com/USAJOBS/Help/files/1029049/How.to.contact.USAJOBS-updates_20170524.docx)

**Comment by humancompanion** [comment]
@dalenard21 - You can make the updates. The file is https://github.com/USAJOBS/Help/blob/master/how-to/contact-usajobs.md

**Comment by dalenard21** [comment]
Updates made.  Will go out with next release. Issue closed.
