### ISSUE TITLE
For PDFs show icon and file size

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#233]
We need a treatment for this. This suggestion is form Foresee.

**Comment by humancompanion** [comment]
![screen shot 2017-07-18 at 8 59 12 am](https://user-images.githubusercontent.com/352987/28321203-abde054e-6ba0-11e7-9160-cf66fa14fdc0.png)

**Comment by humancompanion** [comment]
account/profile/eligibility/federal-employment/index.md
46:You must provide information about your pay, series and grade level if you’re a current or former federal employee. This information can be found on a recent [SF-50](https://www.opm.gov/forms/pdfimage/sf50.pdf){:target="_blank"} (Notification of Personnel Action).

application/documents/forms.md
17:* [OPM 1203-FX – Occupational Questionnaire](https://www.opm.gov/forms/pdf_fill/OPM1203FX.pdf){:target="_blank"}
23:* [OF-306 – Declaration for Federal Employment](https://www.opm.gov/forms/pdf_fill/OF0306.pdf){:target="_blank"}
30:* [SF-15 – Application for 10-point Veterans Preference](https://www.opm.gov/forms/pdf_fill/SF15.pdf){:target="_blank"}

fair-and-transparent/financial-suitability.md
17:For more information, [read Mythbuster on Federal Hiring Policies](https://hru.gov/Studio_Recruitment/tools/Mythbuster_on_Federal_Hiring_Policies.pdf)

fair-and-transparent/index.md
9:For more information, [read Mythbuster on Federal Hiring Policies](https://hru.gov/Studio_Recruitment/tools/Mythbuster_on_Federal_Hiring_Policies.pdf)
21:For more information, [read Mythbuster on Federal Hiring Policies](https://hru.gov/Studio_Recruitment/tools/Mythbuster_on_Federal_Hiring_Policies.pdf)

fair-and-transparent/signature-false-statements.md
19:For more information, [read Mythbuster on Federal Hiring Policies](https://hru.gov/Studio_Recruitment/tools/Mythbuster_on_Federal_Hiring_Policies.pdf)

**Comment by dalenard21** [comment]
@humancompanion - I looked at the U.S. Design Web Standards and they don't specify how to identify file type and size for documents, etc., but they do this with some of their links.  

Here's an example:  https://standards.usa.gov/getting-started/designers/
Download design files (Illustrator)

They don't include file size. They DO include a download icon before the link, but I don't think we link to any zip files directly.

**My recommendation for USAJOBS**

[File name](URL to file){:target="_blank"}(File type, File size)

Example: [OPM 1203-FX – Occupational Questionnaire](https://www.opm.gov/forms/pdf_fill/OPM1203FX.pdf){:target="_blank"}(PDF, 2.1 MB)

Thoughts?

**Comment by humancompanion** [comment]
@dalenard21 - Your example is perfect. Let's go with that.

**Comment by dalenard21** [comment]
Pages updated.  Issue closed.
