### ISSUE TITLE
Job announcement: Bargaining unit position

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#240]
I've stubbed out faq/job-announcement/bargaining-units/ and now it just needs the content improved and Tracy to approve.

**Comment by dalenard21** [comment]
@humancompanion I don't see the bargaining unit faq under the job announcement folder.  Is it somewhere else?

**Comment by humancompanion** [comment]
@dalenard21 - I had originally put the file in working-in-government and forgot to move it. In Jekyll the permalink in the yaml front matter determines where it shows up in the site irrespective of where it lives on the file system. Sorry about that, it's placement in the filesystem now matches where it appears in the site.

**Comment by humancompanion** [comment]
Reviewed by Lauren and good to go for publishing.
