### ISSUE TITLE
Add Release Notes for Job Seekers to the Help Center for Each Release

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#248]
Each release should have a file in Help to detail what job seekers can expect to see changing in the new release.

**Comment by KatMullens-work** [comment]
Each release should have a canonical URL

**Comment by humancompanion** [comment]
There isn't anything user visible to talk about in this release so I'll add this with the next release.

**Comment by dalenard21** [comment]
@danthibodeau this was something that Kat submitted a long time ago and we never got around to it.  Is this something you'd like to see?

**Comment by danthibodeau** [comment]
This is something we used to do, but I'm not sure if it's still desired. If it comes back up, we can always open a new issue.

**Comment by dalenard21** [comment]
Sounds good. We'll close this issue for now.
