### ISSUE TITLE
FAQ: Jobs not listed on USAJOBS

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#252]
According to this thread, https://www.govloop.com/forums/topic/what-federal-jobs-are-not-on-usajobs/, we used to have a FAQ, https://help.usajobs.gov/index.php/Determining_the_Right_Career_Path_for_You, that detailed excepted service agencies. The founder of GovLoop goes on to list a more complete list of job boards elsewhere. At the very least this helps seed our agency audit for career sites. But, I'd like to see this FAQ return and list this table:

<table class="wikitable">
<tbody>
<tr>
<th>Mission</th>
<th>Agency Home Page</th>
<th>Employment Information Page</th>
</tr>
<tr>
<th>Agriculture</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Animal Plant and Health Inspection Service (USDA)</td>
<td><a href="http://www.aphis.usda.gov/career_opportunities/" class="external free" target="_blank" rel="nofollow">http://www.aphis.usda.gov/career_opportunities/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Botanic Garden</td>
<td><a href="http://www.usbg.gov/education/get-involved.cfm" class="external free" target="_blank" rel="nofollow">http://www.usbg.gov/education/get-involved.cfm</a></td>
</tr>
<tr>
<td></td>
<td>Foreign Agriculture Service (USDA)</td>
<td><a href="http://www.fas.usda.gov/admin/jobs/jobs.asp" class="external free" target="_blank" rel="nofollow">http://www.fas.usda.gov/admin/jobs/jobs.asp</a></td>
</tr>
<tr>
<th>Arts/Humanities</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>U.S. Botanic Garden</td>
<td><a href="http://www.usbg.gov/education/get-involved.cfm" class="external free" target="_blank" rel="nofollow">http://www.usbg.gov/education/get-involved.cfm</a></td>
</tr>
<tr>
<th>Commerce</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>International Trade Administration (DOC)</td>
<td><a href="http://www.ita.doc.gov/jobs/" class="external free" target="_blank" rel="nofollow">http://www.ita.doc.gov/jobs/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Patent and Trademark Office (DOC)</td>
<td><a href="http://usptocareers.gov/" class="external free" target="_blank" rel="nofollow">http://usptocareers.gov/</a></td>
</tr>
<tr>
<th>Courts</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Supreme Court of the United States</td>
<td><a href="http://www.supremecourtus.gov/jobs/jobs.html" class="external free" target="_blank" rel="nofollow">http://www.supremecourtus.gov/jobs/jobs.html</a></td>
</tr>
<tr>
<td></td>
<td>Judicial Panel on Multidistrict Litigation</td>
<td><a href="http://www.jpml.uscourts.gov/Job_Opportunities/job_opportunities.html" class="external free" target="_blank" rel="nofollow">http://www.jpml.uscourts.gov/Job_Opportunities/job_opportunities.html</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Bankruptcy Courts</td>
<td><a href="http://www.uscourts.gov/careers/" class="external free" target="_blank" rel="nofollow">http://www.uscourts.gov/careers/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Court of Appeals for the Federal Circuit</td>
<td><a href="http://www.cafc.uscourts.gov/mploymnt.html" class="external free" target="_blank" rel="nofollow">http://www.cafc.uscourts.gov/mploymnt.html</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Court of International Trade</td>
<td><a href="http://www.cit.uscourts.gov/hr/employment.htm" class="external free" target="_blank" rel="nofollow">http://www.cit.uscourts.gov/hr/employment.htm</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Courts of Appeals</td>
<td><a href="http://www.uscourts.gov/careers/" class="external free" target="_blank" rel="nofollow">http://www.uscourts.gov/careers/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. District Courts</td>
<td><a href="http://www.uscourts.gov/careers/" class="external free" target="_blank" rel="nofollow">http://www.uscourts.gov/careers/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Court of Appeals for the Armed Forces</td>
<td><a href="http://www.armfor.uscourts.gov/Clerkships.htm#1" class="external free" target="_blank" rel="nofollow">http://www.armfor.uscourts.gov/Clerkships.htm#1</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Court of Appeals for Veterans Claims</td>
<td><a href="http://www.armfor.uscourts.gov/Clerkships.htm#1" class="external free" target="_blank" rel="nofollow">http://www.armfor.uscourts.gov/Clerkships.htm#1</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Court of Federal Claims</td>
<td><a href="http://www.uscfc.uscourts.gov/job-opportunitiesemployment" class="external free" target="_blank" rel="nofollow">http://www.uscfc.uscourts.gov/job-opportunitiesemployment</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Tax Court</td>
<td><a href="http://www.ustaxcourt.gov/employment.htm" class="external free" target="_blank" rel="nofollow">http://www.ustaxcourt.gov/employment.htm</a></td>
</tr>
<tr>
<td></td>
<td>Administrative Office of the United States Courts</td>
<td><a href="http://www.uscourts.gov/employment/ao/index.html" class="external free" target="_blank" rel="nofollow">http://www.uscourts.gov/employment/ao/index.html</a></td>
</tr>
<tr>
<td></td>
<td>Federal Judicial Center</td>
<td><a href="http://www.fjc.gov/" class="external free" target="_blank" rel="nofollow">http://www.fjc.gov</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Sentencing Commission</td>
<td><a href="http://www.ussc.gov/Jobs.htm" class="external free" target="_blank" rel="nofollow">http://www.ussc.gov/Jobs.htm</a></td>
</tr>
<tr>
<th>Education</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>White House Commission on Presidential Scholars [Presidential Scholars Program]</td>
<td><a href="http://www.ed.gov/programs/psp/commission.html" class="external free" target="_blank" rel="nofollow">http://www.ed.gov/programs/psp/commission.html</a></td>
</tr>
<tr>
<th>Energy</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>National Nuclear Security Administration (DOE)</td>
<td><a href="http://humancapital.doe.gov/jobs/" class="external free" target="_blank" rel="nofollow">http://humancapital.doe.gov/jobs/</a></td>
</tr>
<tr>
<td></td>
<td>Nuclear Regulatory Commission (DOE)</td>
<td><a href="http://www.nrc.gov/about-nrc/employment.html" class="external free" target="_blank" rel="nofollow">http://www.nrc.gov/about-nrc/employment.html</a></td>
</tr>
<tr>
<td></td>
<td>Tennessee Valley Authority</td>
<td><a href="http://www.tva.gov/employment/" class="external free" target="_blank" rel="nofollow">http://www.tva.gov/employment/</a></td>
</tr>
<tr>
<td></td>
<td>Northwest Power Planning Council</td>
<td><a href="http://www.nwcouncil.org/about/employment.htm" class="external free" target="_blank" rel="nofollow">http://www.nwcouncil.org/about/employment.htm</a></td>
</tr>
<tr>
<td></td>
<td>Delaware River Basin Commission</td>
<td><a href="http://www.state.nj.us/drbc/jobs.htm" class="external free" target="_blank" rel="nofollow">http://www.state.nj.us/drbc/jobs.htm</a></td>
</tr>
<tr>
<td></td>
<td>National Park Foundation</td>
<td><a href="http://www.nationalparks.org/about/employment/" class="external free" target="_blank" rel="nofollow">http://www.nationalparks.org/about/employment/</a></td>
</tr>
<tr>
<td></td>
<td>Susquehanna River Basin Commission</td>
<td><a href="http://www.srbc.net/about/employ.htm" class="external free" target="_blank" rel="nofollow">http://www.srbc.net/about/employ.htm</a></td>
</tr>
<tr>
<td></td>
<td>Valles Caldera Trust &amp; Preserve</td>
<td><a href="http://www.vallescaldera.gov/about/employment/" class="external free" target="_blank" rel="nofollow">http://www.vallescaldera.gov/about/employment/</a></td>
</tr>
<tr>
<th>Federal Mgt / Oversight</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Office of Government Ethics</td>
<td><a href="http://www.usoge.gov/careers.aspx" class="external free" target="_blank" rel="nofollow">http://www.usoge.gov/careers.aspx</a></td>
</tr>
<tr>
<td></td>
<td>General Services Administration</td>
<td><a href="http://www.gsa.gov/" class="external free" target="_blank" rel="nofollow">http://www.gsa.gov</a></td>
</tr>
<tr>
<td></td>
<td>Postal Regulatory Commission</td>
<td><a href="http://www.prc.gov/" class="external free" target="_blank" rel="nofollow">http://www.prc.gov/</a></td>
</tr>
<tr>
<td></td>
<td>Social Security Advisory Board</td>
<td><a href="http://www.ssab.gov/Internship.html" class="external free" target="_blank" rel="nofollow">http://www.ssab.gov/Internship.html</a></td>
</tr>
<tr>
<th>Finance</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Federal Reserve System</td>
<td><a href="http://www.federalreserve.gov/careers/default.htm" class="external free" target="_blank" rel="nofollow">http://www.federalreserve.gov/careers/default.htm</a></td>
</tr>
<tr>
<td></td>
<td>Health Research Service Administration (VA)</td>
<td><a href="http://www.hrsa.gov/about/jobs.htm" class="external free" target="_blank" rel="nofollow">http://www.hrsa.gov/about/jobs.htm</a></td>
</tr>
<tr>
<td></td>
<td>Federal Laboratory Consortium for Technology Transfer</td>
<td><a href="http://www.federallabs.org/employment/" class="external free" target="_blank" rel="nofollow">http://www.federallabs.org/employment/</a></td>
</tr>
<tr>
<th>International</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>U.S. Agency for International Development</td>
<td><a href="http://www.usaid.gov/careers/" class="external free" target="_blank" rel="nofollow">http://www.usaid.gov/careers/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Foreign Service (U.S. Department of State)</td>
<td><a href="http://careers.state.gov/local-employment/employment.html" class="external free" target="_blank" rel="nofollow">http://careers.state.gov/local-employment/employment.html</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Mission to the United Nations ( U.S. Department of State)</td>
<td><a href="http://usun.state.gov/" class="external free" target="_blank" rel="nofollow">http://usun.state.gov</a></td>
</tr>
<tr>
<td></td>
<td>Panama Canal Commission</td>
<td><a href="http://www.pancanal.com/eng/hr/index.html" class="external free" target="_blank" rel="nofollow">http://www.pancanal.com/eng/hr/index.html</a></td>
</tr>
<tr>
<td></td>
<td>International Broadcasting Bureau</td>
<td><a href="http://www.bbg.gov/about/jobs/index.html" class="external free" target="_blank" rel="nofollow">http://www.bbg.gov/about/jobs/index.html</a></td>
</tr>
<tr>
<td></td>
<td>Peace Corps</td>
<td><a href="http://www.peacecorps.gov/" class="external free" target="_blank" rel="nofollow">http://www.peacecorps.gov</a></td>
</tr>
<tr>
<th>Policy</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Election Assistance Commission</td>
<td><a href="http://www.eac.gov/about/employment" class="external free" target="_blank" rel="nofollow">http://www.eac.gov/about/employment</a></td>
</tr>
<tr>
<td></td>
<td>Library of Congress</td>
<td><a href="http://www.loc.gov/hr/employment/index.php" class="external free" target="_blank" rel="nofollow">http://www.loc.gov/hr/employment/index.php</a></td>
</tr>
<tr>
<td></td>
<td>U.S. House of Representatives</td>
<td><a href="http://www.house.gov/cao-hr/" class="external free" target="_blank" rel="nofollow">http://www.house.gov/cao-hr/</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Senate</td>
<td><a href="http://www.senate.gov/reference/Index/Employment.htm" class="external free" target="_blank" rel="nofollow">http://www.senate.gov/reference/Index/Employment.htm</a></td>
</tr>
<tr>
<th>Security</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Federal Air Marshall Service (DHS)</td>
<td><a href="http://www.tsa.gov/join/index.shtm" class="external free" target="_blank" rel="nofollow">http://www.tsa.gov/join/index.shtm</a></td>
</tr>
<tr>
<td></td>
<td>Federal Emergency Management Agency (DHS)</td>
<td><a href="http://www.fema.gov/" class="external free" target="_blank" rel="nofollow">http://www.fema.gov</a></td>
</tr>
<tr>
<td></td>
<td>Transportation Security Administration (DHS)</td>
<td><a href="http://www.tsa.gov/join/index.shtm" class="external free" target="_blank" rel="nofollow">http://www.tsa.gov/join/index.shtm</a></td>
</tr>
<tr>
<td></td>
<td>U.S. Secret Service (DHS)</td>
<td><a href="http://www.secretservice.gov/opportunities.shtml" class="external free" target="_blank" rel="nofollow">http://www.secretservice.gov/opportunities.shtml</a></td>
</tr>
<tr>
<td></td>
<td>Central Intelligence Agency</td>
<td><a href="https://www.cia.gov/careers/opportunities/index.html" class="external free" target="_blank" rel="nofollow">https://www.cia.gov/careers/opportunities/index.html</a></td>
</tr>
<tr>
<td></td>
<td>Defense Intelligence Agency (DOD)</td>
<td><a href="http://www.dia.mil/employment/index.html" class="external free" target="_blank" rel="nofollow">http://www.dia.mil/employment/index.html</a></td>
</tr>
<tr>
<td></td>
<td>National Security Agency (DOD)</td>
<td><a href="http://www.nsa.gov/careers/index.shtml" class="external free" target="_blank" rel="nofollow">http://www.nsa.gov/careers/index.shtml</a></td>
</tr>
<tr>
<td></td>
<td>United States Capitol Police</td>
<td><a href="http://www.uscapitolpolice.gov/apply.php" class="external free" target="_blank" rel="nofollow">http://www.uscapitolpolice.gov/apply.php</a></td>
</tr>
<tr>
<td></td>
<td>Federal Bureau of Investigation (DOJ)</td>
<td><a href="http://www.fbijobs.gov/" class="external free" target="_blank" rel="nofollow">http://www.fbijobs.gov/</a></td>
</tr>
<tr>
<th>Transportation</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Federal Aviation Administration (DOT)</td>
<td><a href="http://www.faa.gov/jobs/" class="external free" target="_blank" rel="nofollow">http://www.faa.gov/jobs/</a></td>
</tr>
<tr>
<td></td>
<td>AMTRAK (National Railroad Passenger Corporation)</td>
<td><a href="http://www.amtrak.com/" class="external free" target="_blank" rel="nofollow">http://www.amtrak.com</a></td>
</tr>
<tr>
<th>Other</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>U.S. Postal Service</td>
<td><a href="http://www.usps.com/" class="external free" target="_blank" rel="nofollow">http://www.usps.com</a></td>
</tr>
</tbody>
</table>

**Comment by dalenard21** [comment]
@mgearley 

Hi Michelle,

We're going through old issues in GitHub and came across this one.  It was something Matt submitted as an issue.  Is this something you'd like to see in our Help Center?  If so, priority?  Or should we close this?

**Comment by mgearley** [comment]
I will defer to Dan. I am not sure how we can maintain a list of other government entities who are not subjected to Title 5 postings. Many of the agencies listed do post some opportunities on USAJOBS, but not all of their opportunities.

**Comment by danthibodeau** [comment]
I'm not sure how we used to keep it updated, @jdstill used to do that. But sounds like there was a GovLoop list that had more according to Matt's comment. I'm not sure if people have been asking for it, but I haven't heard much about it lately, so not likely.
