### ISSUE TITLE
Share: Email sharing does not include full link, may not be functional on some PCs

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#257]
The email link we generate in the sharing isn't the full link (it lacks site.baseurl). :-(

Also, @dpboyd reports that the mailto link is not working on his OPM PC laptop. I'm going to try it out on mine now that it is back in my hands tomorrow.

**Comment by humancompanion** [comment]
I did test this out on my PC today and it is working as expected now:

![screenshot 2017-11-14 17 08 46](https://user-images.githubusercontent.com/352987/32807634-83e4750c-c95e-11e7-810c-fd0e0871ddf3.png)

**Comment by dpboyd** [comment]
Ok great! Thanks Matt.

On Nov 14, 2017, at 5:09 PM, Matthew Dingee <notifications@github.com<mailto:notifications@github.com>> wrote:


I did test this out on my PC today and it is working as expected now:

[https://user-images.githubusercontent.com/352987/32807634-83e4750c-c95e-11e7-810c-fd0e0871ddf3.png]<https://user-images.githubusercontent.com/352987/32807634-83e4750c-c95e-11e7-810c-fd0e0871ddf3.png>
