### ISSUE TITLE
Change account to profile in articles

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#277]
We missed an instance of "account" in the "How to update an application" article. Please update "account" to "profile". Thanks.

**Comment by humancompanion** [comment]
How to update an application and How to upload and submit through USAJOBS.

**Comment by dalenard21** [comment]
@humancompanion 

Elsewhere we use "Sign into your USAJOBS profile."  I think this works okay. I'm not sure if people know the difference between account and profile. You are signing into your profile, via login.gov.  But, if you think the language is not quite right, then I suggest we use "Sign into USAJOBS." everywhere.
