### ISSUE TITLE
Re-write the "Get Started" page 

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#279]
@dalenard21 - We'll need to re-write the "Get Started" page for the login.gov transition. We either need to replace account or be clear about login.gov account vs. USAJOBS profile.

**Comment by dalenard21** [comment]
@humancompanion here's a revised Get Started page.  We can revise post login if we want to change our approach.
[Help-center-get-started_20180118.docx](https://github.com/USAJOBS/Help/files/1643706/Help-center-get-started_20180118.docx)
