### ISSUE TITLE
USA Jobs API question

### ISSUE THREAD

**Issue by jonathaneckman** [USAJOBS/Help#283]
Hello USA Jobs team. Our application is attempting to use your API and we had a question. I was unable to find a better place to reach out to provide feedback and ask questions about for your API. Point me in the right direction if this is not the place. 

My question is are there any additional requirements needed to query a code list from our application besides what is already [documented](https://developer.usajobs.gov/API-Reference/GET-codelist-occupationalseries)? I am able to get a response using the browser or postman, but see CORS errors when a request originates from our app.

**Comment by jdstill** [comment]
Hi Jonathan,

Please submit your question to vendor-help@usajobs.gov<mailto:vendor-help@usajobs.gov>

Thanks

-john
