### ISSUE TITLE
Revise hiring path intro language

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#287]
Remove 'preference' and revise the language to not mislead people.

On landing page, under Explore Hiring Paths, and in the Help Center https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/ 

update this language to not say 'preference'.
"The Federal Government offers unique hiring paths (also known as a hiring authority) to help hire individuals that represent our diverse society. If you fall under one of these groups of people you may be eligible to receive preference when applying for jobs."

**Comment by dalenard21** [comment]
@humancompanion 

Let's use this language on the unique hiring path index page in the Help Center.

The Federal Government offers unique hiring paths to help hire individuals that represent our diverse society.  Learn more about each hiring path and your eligibility.

**Comment by dalenard21** [comment]
@humancompanion do you know if this was done?  I don't see it on the live site, but perhaps it's going out with the next release?

We need to update it in the Help Center:
https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/

I didn't see where I could update it on the index.md page though.

**Comment by humancompanion** [comment]
Fixed here 1aa700ab11e887764f9719095c6957f9ff5caf3e.
