### ISSUE TITLE
Please Update Transcript Article Language to Include Digital v. Hard Copy Transcript Guidance

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#293]
Debbie LeNard [10:43 AM]
this is what we have on help center for transcripts. https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/transcripts/

Matthew Dingee [10:53 AM]
Sitting with Carrie on USA Staffing - For appointment they have to have official physical copies but, not for applying. Digital is completely fine for applying.

Matthew Dingee [11:19 AM]
If we don't already then sure. Please file an issue for us in github.

<slack edited for relevant content. Discussion was this morning 27 March 2018>

**Comment by dalenard21** [comment]
added this language:

Can I submit an unofficial copy of my transcript?
The job announcement will tell you if you can submit a 'copy' or 'unofficial copy' of your transcript or if it needs to be a 'certified copy'. Most of the time it's okay to submit an unofficial copy of your transcript when you first apply to the job. If you get further along in the application process, you may need to submit an 'certified official' and unopened copy from your academic institute.

Change will go out the next time help center is pushed out.  

Closing issue.

**Comment by KatMullens-work** [comment]
Thank you!!


-----------
Kathlene “Kat” Mullens, MLHR, SPHR, BSBA
USAJOBS Engagement Specialist and Social Media

U.S. Office of Personnel Management
Mobile:  202.491.6958
Kathlene.Mullens@OPM.gov
