### ISSUE TITLE
SES Hiring path page - revise language 

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#294]
Per email from Dan:

Revise the language on the SES hiring path page to talk about "Senior executives - other".  Just call this out and perhaps use larger heading about the other types of senior exec positions that are NOT in the SES.

**Comment by dalenard21** [comment]
Will update the page as follows:

Replace this paragraph: 
"Are there other executive level jobs that aren’t in the SES?
Yes. Agencies in the competitive or excepted service may have executive level jobs. In the job announcement, look for the This job is open to section. When a job is considered an executive level job, you’ll see this icon <icon>".

Use this content instead:
## Other senior executive level jobs
Not all senior executive level jobs are in the SES.  Agencies in the competitive or excepted service may have executive level jobs, where you may not have to meet the same qualification requirements as in the SES. 

In the job announcement, look for the **This job is open** to section. When a job is considered an executive level job, you’ll see the **Senior Executives – Other icon** <insert icon>.  You can also select the **Senior Executives – Other** filter in search. Your results will display all senior executive level jobs that aren’t in the SES.

**Comment by dalenard21** [comment]
made edits to the page, but changed "Senior Executives - Other" to "Other senior executives", because that's the label used in search filters.

@humancompanion please double check the changes I did - don't want to mess up the html.

**Comment by humancompanion** [comment]
Changes look good. Ready to deploy.
