### ISSUE TITLE
Help Center - How does application process work updates

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#295]
Need to update the content on this page:

https://www.usajobs.gov/Help/faq/application/process/

to include login.gov and other edits that we're making to the application process tab on the landing page.

**Comment by KatMullens-work** [comment]
Adding this content from @dalenard21

**Comment by humancompanion** [comment]
@dalenard21 made these changes starting with this commit 162c9264722d8f68c7e8dc4f8e489df35571f4ad. Verified the page is up-to-date.
