### ISSUE TITLE
Update PRA page

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#299]
Our page on PRA has an incomplete sentence in it and does not have a plain language explanation, which we feature on a number of other Fair & Transparent pages. This page is linked to from Profile - Demographics.

https://www.usajobs.gov/Help/paperwork-reduction-act/

**Comment by dalenard21** [comment]
Updated the content.  Julie reviewed it.  Made the changes in GitHub and it will go out with the next release.  Issue closed.
