### ISSUE TITLE
Create new Profile content and redirects

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#307]
@dalenard21 and I need to create some new content and move some content around to support Profile changes. 

* [x] Create Help/how-to/account/profile/education/ (Use & revise content from Help/how-to/account/documents/resume/build/education/)
* [x] Create Help/how-to/account/profile/hiring-paths/
* [x] Create Help/how-to/account/profile/experience/work/ (Use & revise content from Help/how-to/account/documents/resume/build/experience/)
* [x] Create Help/how-to/account/profile/experience/federal/ (Use & revise content from Help/how-to/account/profile/eligibility/federal-employment/)
* [x] Create Help/how-to/account/profile/experience/military/ (Use & revise content from Help/how-to/account/profile/eligibility/military-service/)
* [x] Create Help/how-to/account/profile/searchable/ (Use & revise content from Help/how-to/account/documents/resume/searchable/)
* [x] Create "How is working for the government different than the private sector?"
* [x] Create "How long does it take to get a federal job?"

We may need to add more but, these are a start. We're fairly certain not every section will warrant an entire help article. Most of the forms can be explained by content in the Help right-rail on the form itself.

**Comment by humancompanion** [comment]
I stubbed out two new pages in 5ac1c9b93e4619478c1cfb284b4ffda473b20eff for education and hiring paths. More to follow as needed.

cc @dalenard21

**Comment by dalenard21** [comment]
All of this content has been updated. Closing issue.
