### ISSUE TITLE
Additional Options for Users with Limited Cell/Phone Service

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#308]
It was suggested we add information on free texting apps to https://www.usajobs.gov/Help/how-to/account/limited-access/
---
From facebook: there are free apps to obtain (Text Me)(That’s the name) which will provide a phone number and works when you have WiFi. I recently assisted person who communicates by ASL and had no use for regular cell phone service.
---
We would want a little generic info on ensuring they keep access and a few examples of products people may wish to consider (like we do for authenticator apps).

**Comment by dalenard21** [comment]
@KatMullens-work @humancompanion 

Question - would someone use this option if they don't have a texting plan with their cell phone?  And this would be a way for them to receive the one-time security code outside of their cell plan?  I just need to understand better how this would work with login.

**Comment by KatMullens-work** [comment]
Hi Deb:

If they don’t have  a texting plan, are using their phone in airplane mode on wifi (like on a plane), are out of texting service area (I did work in upper New England a few years ago and they still use pagers because cell signals don’t work) but have wifi, which I think also exists on some military installations.

Those are a few of the use cases I can think of. Matt may have others.

Thanks,
kat

**Comment by dalenard21** [comment]
Updated the help center page to include info about free text messaging apps. Issue closed.
