### ISSUE TITLE
Hiring Paths: Students & Recent Grads page could mention Public Service Loan Forgiveness (PSLF) Program

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#309]
One way government competes for talent with the private sector is to offer student loan forgiveness. The Department of Education program applies to Federal employment and thus we should highlight it on our hiring paths page.

https://studentaid.ed.gov/sa/repay-loans/forgiveness-cancellation/public-service

**Comment by dalenard21** [comment]
closing this issue. opened new issue in team design repo https://github.com/USAJOBS/team-design/issues/68
