### ISSUE TITLE
Edit qualifying-education to add details around foreign education

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#312]
Suggestion from Recruiter-Help discussed on Slack on 5/21/18: 

Dywane Boyd [Today at 2:15 PM]
in #support-feedback

Good evening! I wanted to take the opportunity to provide a suggestion for an enhancement of information on the USAJOBS Help Center. For some background, NASA is currently considering adding information about foreign education to all of our vacancy announcements. As we discussed this, I decided to bring this issue to USAJOBS in the hope that we could work out a government-wide solution since is this is an issue that all agencies face, not just NASA. It would be a big help to both job seekers and agencies to have accurate, consistent information available to job seekers. This led me to offer the following information and suggestions.

When I looked for information on foreign education on USAJOBS, the only information I could find appears under this FAQ: https://www.usajobs.gov/Help/faq/application/qualifications/qualifying-education/

I suggest updating this information to include more information for job seekers with foreign education, to include how foreign education is evaluated and how applicants should indicate this education on their resumes. OPM's General Schedule Qualification Policy (on the OPM website) offers more in-depth guidance for agencies, which could be distilled to more applicant friendly language.

I also would like to recommend updating the education text box that appears on USAJOBS vacancy announcements:

[cid:image001.jpg@01D3EC6E.5B5410B0]

While the statement shown in the box is true, it doesn't give complete information. Foreign education can be considered for federal employment provided that the education has been evaluated. My suggestion is to update this language to read something along these lines:

If you are relying on your education to meet qualification requirements:

In most cases, education must be accredited by an accrediting institution recognized by the U.S. Department of Education in order for it to be credited towards qualifications. Therefore, provide only the attendance and/or degrees from schools accredited by accrediting institutions recognized by the U.S. Department of Education<http://www.ed.gov/admins/finaid/accred/>. If you have completed education outside the United States, please visit our Help Center to learn how your education can be used for qualify for federal employment.

Failure to provide all of the required information as stated in this vacancy announcement may result in an ineligible rating or may affect the overall rating.

2 replies
Michelle Earley [22 hours ago]
@lauren33 @matthew.dingee I feel like this requirement came up through the agency JOA/HP feedback, so we can consider it for the help center updates. We can also look at the JOA language.

Matthew Dingee [22 hours ago]
We discussed this a week or two ago. We plan to add a link to the Help Center (something like "Learn more bout foreign education"). I believe a ticket was filed at that time.

**Comment by KatMullens-work** [comment]
I see content about foreign education here: https://www.usajobs.gov/Help/how-to/account/profile/education/

**Comment by Piglady64** [comment]
We talked about this back in May when we got this initially. I provided a link to the Department of Education and had it verified by the first person who made this suggestion. I am not sure why it is coming up again.

**Comment by KatMullens-work** [comment]
The issue is still open so I was looking at it.


Kat

**Comment by dalenard21** [comment]
@Piglady64 can this issue be closed?

**Comment by Piglady64** [comment]
@dalenard21 We took care of this. You can close it.

**Comment by dalenard21** [comment]
closing issue.
