### ISSUE TITLE
Add help page on how to print

### ISSUE THREAD

**Issue by jdstill** [USAJOBS/Help#313]
We have an enhancement request from NASA to add information into the Help Center on how to print a JOA.  They report that Pathways applicants (and/or their parents) are not aware of this functionality and are using the browsers print function instead of the print button in the announcement

**Comment by KatMullens-work** [comment]
Suggest the following draft content:

Item name: Printing Job Announcements

USAJOBS offers a convenient way to print job announcements. From any job announcement, you can click on the "print" link (located under the "Apply" button) and a new window with a printable version of the job announcement will open. When you're done printing, just close the new window.
