### ISSUE TITLE
Update "Open to the public" to support Profile changes

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#314]
There are a few pages we need to update in the Help Center to support Profile changes.

1. Change "Open to the public" to "The public" throughout.
https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/public/
https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/
https://www.usajobs.gov/Help/how-to/job-announcement/this-job-is-open-to/
https://www.usajobs.gov/Help/how-to/job-announcement/second-announcement/ (just unlink the 'open to')
https://www.usajobs.gov/Help/faq/application/eligibility/
https://www.usajobs.gov/Help/how-to/search/filters/hiring-path/
https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/federal-employees/

May   be other pages and will add as they pop up.

**Comment by dalenard21** [comment]
As of 7/13, and per development team, this change will not be going out with the initial profile changes, so we don't need to update these help center pages yet.

**Comment by humancompanion** [comment]
The search filter has not changed, but I believe it has changed just about everywhere else.

**Comment by dalenard21** [comment]
It's been over a year since this issue was created.  The search filter is still "Open to the public", but everywhere else is okay. Closing this issue. Will create a new one if there's a strong need to update the search filter label.
