### ISSUE TITLE
Update content for login.gov & authentication apps

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#316]
Request from support desk for login.gov content updates:

"Also, it would be awesome if Login.gov could include a help page with screen shots that show the user how to use the new process of creating an account using an Authentication Application.. something similar to their current “How do I create an account with login.gov?” page..
https://login.gov/help/creating-an-account/how-do-i-create-an-account-with-logingov/

Old Trello URL: https://trello.com/c/F6uX3fCm/1228-help-center-update-content-for-logingov-authentication-apps

@dalenard21 may have done this already but need to move the Help Center Trello cards to github for our mass migration.

**Comment by dalenard21** [comment]
login.gov recently updated their help page on how to create an account and included a screenshot of using an authentication application.

https://login.gov/help/creating-an-account/how-do-i-create-an-account-with-logingov/

Issue closed.
