### ISSUE TITLE
Leverage content from VA Welcome Kit

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#318]
Colleagues in The Lab have created this VA Welcome Kit:

https://www.vets.gov/va_welcomekit_color.pdf

There is content that I feel is ripe for our use in the Veterans' hiring path page as well as, potentially, in new user on-boarding. I'm curious as to what others think. Let's review it and discuss.

Old Trello URL: https://trello.com/c/fxyCSmRs/1204-help-center-profile-leverage-content-from-va-welcome-kit

**Comment by dalenard21** [comment]
Moving this issue into design team repo. https://github.com/USAJOBS/team-design/issues/70

Closing this issue.

**Comment by Piglady64** [comment]
@dalenard21 I was curious about this "welcome kit". I clicked on the link you have above and it didn't work. Here is the right link https://www.va.gov/welcome-kit/
