### ISSUE TITLE
Change phone number/help topic suggestion

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#322]
From: Chapman, Carla
Sent: Wednesday, August 01, 2018 7:46 AM
To: Thibodeau, Dan
Subject: change phone number/help topic suggestion

Good morning!

I was wondering if we have a help page dedicated to the phone number change issue.. it would be helpful if most of these tickets came in under the same title/help topic since we get so many of these now, especially for triaging purposes.  And could it perhaps be listed on the initial Help page as one of the top 6 next to "How to..."?  With this being a good bit of our tickets, I'd like users to get straight to the page they need.  As of right now, they come in under all sorts of titles because they are clicking around the Help Center aimlessly and not finding a topic for their issue.  Perhaps a page titled: How to update the phone number where the security code is sent.. or something to that affect.. just so they understand there's a difference between the number in their profile and the number in login.gov<http://login.gov>, how/where to change it, and if they are unable to sign in in order to change it, then contact us for assistance.  :)

**Comment by dalenard21** [comment]
login.gov does have a page for this question:

https://login.gov/help/changing-settings/how-do-i-change-the-phone-number-i-use-to-sign-in/

However, we can create a page in our help center to point users to login.gov.

**Comment by humancompanion** [comment]
@dalenard21 - Yeah, I think that's all Carla is really after so that "tickets come in under the same title/help topic".

**Comment by dalenard21** [comment]
Here is the content we can use in our help center. I added an explanation that updating the phone number in login.gov doesn't update it in their profile.  

@humancompanion can you quickly review and stub out the page?  I assume it'll go under "How to>account".
[Help-center-how-to-change-phone-number-you-use-to-sign-in_20170801.docx](https://github.com/USAJOBS/Help/files/2250226/Help-center-how-to-change-phone-number-you-use-to-sign-in_20170801.docx)
