### ISSUE TITLE
Update hiring path search filter content

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#324]
This page doesn't reflect the current hiring path options:

https://www.usajobs.gov/Help/how-to/search/filters/hiring-path/

In particular, the Federal employee option is missing the sub-options we've added. This is the target of the Help link next to the hiring paths search filter.

* [x] Split Federal employee into competitive and excepted sub-sections
* [x] Add career transition
* [x] Split students and recent graduates
* [x] Add base to Land management
* [x] Organize the list into the sub-sections that are in the filters

**Comment by dalenard21** [comment]
@humancompanion I finished this.
