### ISSUE TITLE
About: Update design story text and CTA

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#33]
Tracy has content for us to update on the About page.

**Comment by PeterToohey** [comment]
Change #1:  Last sentence of 'About USAJOBS' section should be changed from:
'USAJOBS is here help you find you find ways to serve' to 'USAJOBS is here to help you find ways to serve.'

Change #2: Under 'What's New at USAJOBS:' please change the design story button to say 'USAJOBS Design System"
The learn more line above the button should read: 'Learn more about the visual style and guidelines we've implemented across the website'
