### ISSUE TITLE
Add definitions for language skill level

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#335]
Update the "How to add languages to your profile" page to include definitions for the language skill level:

Novice
Intermediate
Advanced

Due date: This needs to be live when DOS unpaid internship goes out, but can be added earlier

**Comment by dalenard21** [comment]
This will be worked as part of the open opps help center updates for Students

**Comment by dalenard21** [comment]
@kbwagner @Piglady64 

Here's my first draft of definitions for the new language levels.  I used descriptions from the American Council on Teaching Foreign Language https://www.actfl.org/

They have more specific 'levels' (Advanced - High, Advanced - Mid, etc.), so I tried to combine them into one description for us.  Let me know what you think.

[Help-center-how-to- list-languages-in-profile_v2_20190117.docx](https://github.com/USAJOBS/Help/files/2788536/Help-center-how-to-.list-languages-in-profile_v2_20190117.docx)

**Comment by dalenard21** [comment]
@Piglady64 @kbwagner 

I've updated the How to add languages page in GitHub with the proficiency level definitions.  Can you please review and let me know if you have any feedback?

https://federalist-proxy.app.cloud.gov/site/usajobs/help/how-to/account/profile/languages/

@humancompanion this is ready for the sprint build.  But, we may need to edit before official release.

**Comment by kbwagner** [comment]
@dalenard21 - this looks good. Thanks!

**Comment by Piglady64** [comment]
@dalenard21 this looks good to me too

**Comment by dalenard21** [comment]
Thanks @kbwagner and @Piglady64 

@humancompanion this is ready to go out with the DOS release

**Comment by dalenard21** [comment]
The languages page has been updated in production.

https://www.usajobs.gov/Help/how-to/account/profile/languages/

Issue closed.
