### ISSUE TITLE
Create Basic Troubleshooting Help Center Item

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#337]
Hi Team:

I think an article on basic technical trouble shooting might be useful. I was thinking of something like the following:

When you're using our site, a number of factors could be causing problems you're experiencing. Some basic trouble shooting steps you can take to figure out where the issue may be are:

1. Try using a different Internet Browser in case there's a setting or issue with your browser. You can download many different browsers for free on the internet. For example, try  Safari if you're having problems with Google Chrome. 
2. Try using a different computer. There could be a setting on your computer that is interfering with the proper functioning of our site. You might want to try a friend's computer, a different device you have (a tablet instead of your desktop), or using a computer for free at your local library. USAJOBS is a responsive website which means it will adapt how it works to suit the device you're using.
3. Try using a different network. Some network settings, especially those designed to assure the security of a network, could interfere with the proper functioning of our site. The more security conscious that your network or the organization running it may be, the more likely that certain settings and tools may interfere with USAJOBS working properly. Using a different network could solve the issue; you can also work with your IT team to see if they can change any settings on your network to unblock USAJOBS' functioning. 

If you're still having a technical issue, we want to help address it. Please use the "Contact us" button to reach out to us and include information on your internet browser, if you're using a work or home computer, and if it's a work computer, the name of your employer, and what issue you're having and we'll do our best to help.

**Comment by KatMullens-work** [comment]
Hi @dalenard21 : I wanted to bubble this up as a request to keep it on your radar :)

**Comment by humancompanion** [comment]
@KatMullens-work - Can you capture some examples of what users are asking that prompts this response? Is it trouble uploading docs? Accessing certain parts of the site? Authenticating? Trying to figure out how we'd link other articles to this article.

**Comment by KatMullens-work** [comment]
Most commonly that when they click on the "contact us" button that nothing happens. I think we know this happens a lot in the DOD environment.

**Comment by KatMullens-work** [comment]
There are others but, basically, this would allow me to give people direction on how to get unstuck easily if they are in an environment where something might be interfering.
