### ISSUE TITLE
SPPC Directory Link : no longer available. 

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#342]
https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/individuals-with-disabilities/

![image](https://user-images.githubusercontent.com/25315047/49102244-50adcc80-f246-11e8-995d-09978b6e2762.png)

**Comment by humancompanion** [comment]
This link, https://www.opm.gov/policy-data-oversight/disability-employment/selective-placement-program-coordinator-directory/, is working fine for me. It brings you to a page where you can select a U.S. State or Agency and get the selective placement coordinator. 

I did find some other problems on the page that I fixed that were not related but, there's nothing here left to be done.
