### ISSUE TITLE
Add new Help Center item reminding users to "rebuild" resume builder resumes if they wish to capture profile changes

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#346]
Add new Help Center item reminding users to "rebuild" resume builder resumes if they wish to capture profile changes in a builder resume. Builder resumes are not dynamically updated. Conversely, any resume they have built won't change when they update their profile. this allows users to easily keep a stable of resumes to apply to different jobs and only apply the changes they wish to various resumes.

**Comment by humancompanion** [comment]
We can certainly add this note. But we should prioritize fixing resume builder in the new year. It's the one part of the site un-touched by design and I'd like a chance to fix it up.

**Comment by humancompanion** [comment]
@dalenard21 - This is what I wrote up:

> Updating your resume
>
> In order to capture changes that you have made to your profile you will need to build a new resume. USAJOBS does not automatically update existing resumes. This allows you to easily keep a set of resumes to apply to different jobs and only apply changes when you desire.

Thoughts?

**Comment by KatMullens-work** [comment]
I think it’s more clear if we make sure we’re calling out the resume builder. Just my thoughts.



Updating your USAJOBS Resume Builder resume

In order to capture changes that you have made to your profile, you will need to build a new Resume Builder resume. USAJOBS does not automatically update existing resumes. This allows you to easily keep a set of Resume Builder resumes to apply to different jobs and only apply changes when you desire.

**Comment by humancompanion** [comment]
@KatMullens-work - This is on the "How to build a resume" page and we don't refer to it as Resume Builder in the product or in Help Center. We just say "build a resume".

**Comment by humancompanion** [comment]
Verified as deployed: https://www.usajobs.gov/Help/how-to/account/documents/resume/build/
