### ISSUE TITLE
Update Military Spouse per executive order

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#349]
We received feedback that the eligibility requirements for Military Spouse hiring authority changed.  Per S.2943 - National Defense Authorization Act for Fiscal Year 2017, there are no longer time limitations for military spouses.  We need to remove the content about time limitations.

Here's the change from congress: https://www.congress.gov/bill/114th-congress/senate-bill/2943

The feedback to USAJOBS also said that eligibility no longer requires a PCS move, BUT, we can't find anything in this order that says this.  We will keep the PCS move content until we can reach Policy (who is furloughed).

Change the following on this page: https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/military-spouses/

Remove content "There are time limitations"
Remove bullet about two years
Remove bullet about permanent eligibility if spouse is disabled...because if all time limits are removed, then everyone is permanently eligible.
KEEP "not eligible if you remarry".

**Comment by dalenard21** [comment]
Updated content in github. @humancompanion  this is ready to go out with the next help center release.

**Comment by dalenard21** [comment]
Here's the page in Federalist:
https://federalist-proxy.app.cloud.gov/site/usajobs/help/working-in-government/unique-hiring-paths/military-spouses/

Ready for the 7.6.2 build.

**Comment by humancompanion** [comment]
Lauren is meeting with Policy (MG) next week.

**Comment by dalenard21** [comment]
Lauren met with policy. I've attached the new NDAA CHCO memo that talks about military spouse.  Basically, the criteria is now:

"...the head of an agency may now appoint  non competitively: the spouse of a member of the armed forces on active duty, the spouse of a 100 percent disabled member of the armed forces or a spouse of a deceased member of the armed forces"

[Executive Order 13832 and NDAA FY19 CHOC Memo.pdf](https://github.com/USAJOBS/Help/files/2942788/Executive.Order.13832.and.NDAA.FY19.CHOC.Memo.pdf)

ready for release.

**Comment by humancompanion** [comment]
Verified as deployed: https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/military-spouses/
