### ISSUE TITLE
Closing Type Help Page

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#351]
On https://www.usajobs.gov/Help/how-to/job-announcement/closing-types/#applicant-cut-off there is incorrect text.

The last sentence of Applicant cut-off reads "If they receive 200 applications by 1:30pm EDT, the job will close that same day at 12am EDT." This would be the next day. It should instead read "If they receive 200 applications by 1:30pm EDT, the job will close that same day at 11:59pm EDT."

**Comment by dalenard21** [comment]
@humancompanion @danthibodeau 

I updated the closing type description in GitHub.  This is ready to go out with the next Help Center release.

**Comment by dalenard21** [comment]
Here's the page in federalist

https://federalist-proxy.app.cloud.gov/site/usajobs/help/how-to/job-announcement/closing-types/

**Comment by dalenard21** [comment]
The 'application cut off' description has been updated in production.

https://www.usajobs.gov/Help/how-to/job-announcement/closing-types/#applicant-cut-off

Issue closed.
