### ISSUE TITLE
Fix number on faq/application/process page

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#356]

**Comment by danthibodeau** [comment]
On https://www.usajobs.gov/Help/faq/application/process/ there are two number 4s and no number 5.

**Comment by Piglady64** [comment]
@dalenard21 Can you make these changes?

**Comment by dalenard21** [comment]
@Piglady64 @danthibodeau I made the change in GitHub.  It will go into the production the next time we do a Help Center release.

**Comment by dalenard21** [comment]
This has been updated in production. https://www.usajobs.gov/Help/faq/application/process/

Issue closed.
