### ISSUE TITLE
Hiring Paths - Update Base Management content

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#359]
Review the recent changes to Base Management hiring authority.  See attached.

Make any content changes necessary to the help page: https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/federal-employees/base-management/
[FY 2017 NDAA section 1132--DOD Industrial Base Facility noncomp appts (2).pdf](https://github.com/USAJOBS/Help/files/2961878/FY.2017.NDAA.section.1132--DOD.Industrial.Base.Facility.noncomp.appts.2.pdf)

Do we need to update the hiring path info in Search?

**Comment by dalenard21** [comment]
Here's updated content for Base management hiring path - first draft.  

Need to ask Lauren to review and then will send to Michelle G.
[Hiring-path-base-management_20190312.docx](https://github.com/USAJOBS/Help/files/2996685/Hiring-path-base-management_20190312.docx)

**Comment by dalenard21** [comment]
@humancompanion I updated the html page with the new content, however, I don't know where to update the text that's in the banner at the top.  Currently on the base management page, we have the intro/heading in the banner that says:

"If you’re a current or former term or temporary employee of a Base Management agency, you may be eligible to apply for merit promotion jobs at any federal agency."

and we need to replace it with this revised content:

"If you’re a current or former time-limited employee of a Base Management agency, you may be eligible for a permanent appointment in the competitive service."

Can you do that for me?  And, when I get back you can show me where/how to make those updates so I know in the future.

Thanks.

**Comment by humancompanion** [comment]
@dalenard21 - The file you want to change is this one:
https://github.com/USAJOBS/Help/blob/master/_data/unique-hiring-paths.yml

I've gone ahead and made the change. That file is a YAML file, which is essentially formatted text.
