### ISSUE TITLE
Clarify the "Complete Application" vs "Continue Application" CTA

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#36]
See this page: http://usajobs.github.io/Help/how-to/application/continue/ 

On this page we are instructing a user on how to complete an application if their status is "In Progress". In the instructions, we reference the  "Continue application" button, however, in the new UI the button says "Complete application".  Which one should it be? I say we use "Complete application" and update the How To content.

**Comment by humancompanion** [comment]
Unfortunately, we've used continue elsewhere so continue it is. I've updated the prototype.
