### ISSUE TITLE
Update Help Content

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#364]

**Comment by danthibodeau** [comment]
On https://www.usajobs.gov/Help/working-in-government/myths/resume-scanned-for-keywords/ the paragraph wording says:

Partially true: Real people, Human Resource (HR) specialists, do look at resumes, however some agencies also use an automated system to review resumes. For the agencies that do use an automated system, the resume review process has two parts:

But instead of saying "...system to review resumes." it should instead say "...system to review applications." because resume reviews are not automated, so this confuses users.

**Comment by danthibodeau** [comment]
Thanks Debbie! Our next release should be next Friday (18th). I'm not sure if there are any other changes, but can you have a build ready next week for the dev team?

**Comment by dalenard21** [comment]
Updated in production:

https://www.usajobs.gov/Help/working-in-government/myths/resume-scanned-for-keywords/

Issue closed.
