### ISSUE TITLE
How-to: Create How to Archive an application page

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#37]
Create how to archive an application page.

**Comment by dalenard21** [comment]
@humancompanion 

I have this content ready.  Where should I create the page?

**Comment by humancompanion** [comment]
how-to/application/archive/? Then we'll just not link to it yet and exclude it from search results until it is time to deploy it.

**Comment by humancompanion** [comment]
For 5.6 this page, which covers the current functionality, should be removed:
http://usajobs.github.io/Help/how-to/application/hidden/

**Comment by dalenard21** [comment]
@humancompanion we'll use /Help/how-to/application/archive/

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

I created the How to archive a job application page:;

/how-to/application/archive.md

Let me know if you have any changes.

Closing issue.
