### ISSUE TITLE
Update to Students and Recent Graduates Page

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#370]
Please see the below request to add information about an additional program to the students and recent graduates page (https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/). I have already told him that we would not add this to the home page in the explore hiring paths section since we don't list individual programs there.

https://www.nsep.gov/

Thank you so much for reaching back to me pertaining to our request to have our National Security Education Program (NSEP) featured on the USAJOBS website. As requested, I have attached the above link to our various NSEP initiatives for your review. If you go to the top of our webpage under “Initiatives” the three programs we’d like to highlight under NSEP are our Boren Scholarships, Boren Fellowships and English for Heritage language Speakers Scholarships. Award participants from each of these programs are eligible for non-competitive hire into federal government jobs. In particular, we would like to see NSEP listed under the caption “Students & Recent Graduates” as well as included under the caption “Explore Hiring Paths”.

Please do not hesitate to contact me should you require additional information or clarification.

V/R,

Roy A. Savoy
Executive Liaison Support Officer, NSEP 
(Contractor) 
4800 Mark Center Drive, Ste 08F09-02
Alexandria, VA 22350-7000
Bus: (571) 256-0776
E-mail: roy.a.savoy2.ctr@mail.mil

**Comment by dalenard21** [comment]
Created new issue in team design repo to track this work:  https://github.com/USAJOBS/team-design/issues/205

Closing this issue.
