### ISSUE TITLE
Document Upload Help

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#371]
Dianna would like us to add additional help around document upload. Please review the Staffing help pages below to see what we can add to https://www.usajobs.gov/Help/how-to/account/documents/upload/

https://help.usastaffing.gov/Apply/index.php?title=Uploading_documents_to_your_application

https://help.usastaffing.gov/Apply/index.php?title=Submitting_a_paper_supporting_document

**Comment by Piglady64** [comment]
@danthibodeau We have talked about updating the education page with the other programs. We know that Pathways is not the only student program out there.

**Comment by danthibodeau** [comment]
Thanks @Piglady64! I'm assuming this is for #370. The agency reached out to Michelle, and I told them we would look into adding them, so just wanted to get their request documented :)

**Comment by dalenard21** [comment]
Created a new issue in team design repo to track this work: https://github.com/USAJOBS/team-design/issues/206

Closing this issue.
