### ISSUE TITLE
Students and Recent Graduates Language

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#372]
Possibly update the help page content and search meta-text based on the below conversation between me and @Piglady64:

2.	Recent graduates – This text currently states “Individuals who have graduated from an accredited educational institute or certificate program within the last 2 years or 6 years for Veterans.” The request is to remove the “or 6 years for veterans” because it doesn’t apply to the PMF program. I’m not sure if policy generalized this statement, and if it would be appropriate to update for just the PMF program.
a.	Help text would also need to be updated.

2) I don’t remember anything about the 6 yrs for veterans for the recent grads. However, from a user perspective, there are more programs that do use this than don’t. We have been talking about re-writing the Student and Recent Grad page so we may want to put that there. If we remove the 6 yr for vets I would recommend removing the 2 years from the definition too because we are excluding a large user group in the vets for one program. Just my thoughts.

**Comment by dalenard21** [comment]
Created a new issue in the team design repo to track this work: https://github.com/USAJOBS/team-design/issues/204

Closing this issue.
