### ISSUE TITLE
Update Phone Number Link

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#373]
On https://www.usajobs.gov/Help/how-to/account/change-phone-number/, the link under the first paragraph points to https://login.gov/help/changing-settings/how-do-i-change-the-phone-number-i-use-to-sign-in/, but that provides an error message and needs to be updated.

**Comment by dalenard21** [comment]
Created new issue in team design repo to track this work: https://github.com/USAJOBS/team-design/issues/203

Closing this issue.
