### ISSUE TITLE
OMB PRA Numbers

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#375]
On https://www.usajobs.gov/Help/paperwork-reduction-act/ we note OMB control number 3046-0046 and on https://www.usajobs.gov/Help/privacy/ we note 3206-0219 with their associated expiration dates.

3046-0046 is only for the demographic data, and 3206-0219 is for the profile and resume.

We may want to list both on both pages, as well as their purpose and expiration dates.

**Comment by dalenard21** [comment]
Created a new issue in the Team Design repo, since that's where the design team is tracking their work: https://github.com/USAJOBS/team-design/issues/200

Closing this issue.
