### ISSUE TITLE
How-to: Add saved searches overview doc

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#38]
We need a target for a help icon in saved searches that would cover:

* What a saved search is
* How to create one
* How to edit one
* How to archive one
* How and why to duplicate one
* When and why the automatically archive

I need to know the URL quickly so I can get it into the prototype. I suspect it is just an update to this content: http://usajobs.github.io/Help/how-to/search/save/

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

Content is ready. I sent an email with the word doc, but it's also attached here.  Definitely want feedback on the steps to save a search - I didn't change from what's there today.

[Ho- to-save a-search-profile-dashboard_20160511_v1.0.docx](https://github.com/USAJOBS/Help/files/259785/Ho-.to-save.a-search-profile-dashboard_20160511_v1.0.docx)

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

I migrated the new How to Save a Search overview content to /Help/how-to/search/save/

I'll need to update this content again once we nail down the "Delete" vs "Save/Unsave" vs. "Archive" battle.  Let's not close the issue until that is resolved.

**Comment by humancompanion** [comment]
@dalenard21 - I went with Save/Saved after referring to Google's design which uses the same "start for saving" pattern and uses that text (I knew I saw it somewhere!).

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey @kyhryt 

I've updated the how to save a search content to include saving/deleting by "starring".   I'm still using the heading "Delete a saved search".  I'd like to have a second pair of eyes on that content.

https://github.com/USAJOBS/Help/blob/master/how-to/search/save/index.md

Also, for now the content includes the limit of 10 saved searches.  Once we have the conversation with development we can update as needed.  Let's keep this issue open until then.

**Comment by dalenard21** [comment]
@humancompanion did we ever settle on number of saved searches?  will it remain at 10?  if so, I'll close this out.

**Comment by dalenard21** [comment]
@PeterToohey confirmed that for now users can only save 10 searches.  Content will remain as is.  Issue closed.
