### ISSUE TITLE
How-to: Save a job announcement

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#40]
We need a page that discusses how to understand and use the saved job card/drawer in Profile Dashboard. This page would be the target of a Help link inside of a saved job drawer.

Possible targets:
1. /Help/how-to/job-announcement/save/ - A a little odd since they've already saved the job but, consistent with /Help/how-to/search/save/ which is where I proposed we'd go from a saved search.
2. /Help/how-to/job-announcement/saved/

**Comment by dalenard21** [comment]
@humancompanion , @PeterToohey 

A few questions about how saved jobs works:

1. Do saved jobs expire?  Meaning, do they go away once the job closes?  Or if you apply?
2. Do you get notified if a saved job expires? Either via an alert in the profile dashboard or via email or other way?
3. If you do get notified does it happen before it expires or after?
4. How are saved jobs listed? Most recent saved at the top?

Thanks!

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

I have content ready for How to Save a Job.  It's a bit weird, because I combine the how to save a job with how to understand the saved jobs listing.  It seems silly to have two separate pages.

I can't seem to attach the file here so I'll email it.

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 
Created new page How to Save a Job Announcement: /Help/how-to/job-announcement/save/

Issue closed.
