### ISSUE TITLE
How-to: Filter applications

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#41]
We need to create a page that covers how to filter the list of applications. This page should also cover the list of application states (or link to a page that does) which are documented here: https://github.com/USAJOBS/american-discovery-trail/wiki/Profile-Dashboard#applications

URL options: 

1. /Help/how-to/application/filter/
2. /Help/how-to/home/applications/filter/

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

Sent you an email with the How to filter applications content.  Also attaching here to see if it works.
[How to filter applications_20160510.docx](https://github.com/USAJOBS/Help/files/257726/How.to.filter.applications_20160510.docx)

**Need feedback**
We need to describe the application statuses, but we already do that on the How to check on the status of your application.  I described the high level categories (Advancing, etc) on the How to Filter applications and provided a link over to the How to check status for more details. I don’t really like sending the user to yet another page for the details.  But I also don’t want to repeat the status descriptions in two help center pages. This just leads back to their old ways of having the same content in multiple places.

**Two options and I’d love your feedback on approach**
1.	Combine the how to check application status and how to filter by status – just have one help center page about application status
2.	Keep the two pages and link in between - I do describe how the user can place their cursor on top of the status to get a description (within the filter)

**Comment by dalenard21** [comment]
We made the decision to combine the two pages, How to Filter Applications and How to check on the status of your application into one page.

The updated content is attached, but I also emailed the content to @PeterToohey and @humancompanion.

**Question about URL**

Current url for how to check status: /Help/how-to/application/status/

The URL we used for profile dashboard help icon: /Help/how-to/application/filter/

I think we use the /Help/how-to/application/status/.  So, we need to update the profile dashboard link to point here instead...and can we use an anchor to go directly to the filter part?
[How to filter applications_20160510_v1.1.docx](https://github.com/USAJOBS/Help/files/261796/How.to.filter.applications_20160510_v1.1.docx)

**Comment by humancompanion** [comment]
Verify the "legal records retention policy" verbiage with @danthibodeau. Otherwise, looks good.

**Comment by dalenard21** [comment]
@humancompanion 

I sent an email to Dan about the records retention.  In the meantime, I migrated the content to  /Help/how-to/application/status/.

Let's keep this issue open until @PeterToohey has a chance to review and we hear back from Dan.

**Comment by dalenard21** [comment]
Received feedback from @PeterToohey and made changes to content.

Only update we're waiting on is the language about records retention. I didn't include the phrase about 3 years being our record retention policy.  I'd rather keep it out, unless legal requires it.

**Comment by dalenard21** [comment]
Heard back from Dan and Leon about records retention- we don't need to include it. Leon reached out to and confirmed: " This was confirmed with OPM records management division (Alicia M. Hoefke)"  

On the How to view applications page, the language will remain as "We will permanently remove all applications (active and archived) 36 months after the closing date, regardless of the application status. We recommend printing the announcements for which you have applied if you wish to keep a record of them beyond the 36-month period."

Issue closed.
