### ISSUE TITLE
FAQ > Documents > What not to include

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#46]
The content on What should I not include in my resume needs to match the content that displays in the Account > Documents section.

**Comment by dalenard21** [comment]
@humancompanion , @PeterToohey 

We should update the What Should I Not Include to the following:

If you make your resume searchable, your profile and all resume information will be visible to recruiters searching our resume bank. 

Do not include the following types of information in your profile or resume:
•	Classified or government sensitive information
•	Social Security Number (SSN)
•	Photos of yourself
•	Personal information, other than basic contact information
•	Encrypted and digitally signed documents

I removed personal sensitive information and just used personal information. I think the intent of that bullet is not to include things like your age, gender, religious affiliation, etc. 

Let me know if you have any feedback.

- Debbie

**Comment by humancompanion** [comment]
@dalenard21  - I like the list you provided. I feel that makes it more clear. Can we include that?

"* Personal information, such as age, gender, religious affiliation, etc."

**Comment by dalenard21** [comment]
@humancompanion , yes, let's add that.  I'll make the update and we should also use the same list within the profile dashboard/documents/resume section.

**Comment by dalenard21** [comment]
updated the content on /Help/faq/application/documents/resume/what-to-leave-out/
Issue closed.
