### ISSUE TITLE
Bug: recent graduates filters post twice

### ISSUE THREAD

**Issue by anselmbradford** [USAJOBS/Help#488]
Not sure where to post this (is there a main USAJOBS.gov repo somewhere?)

1. Go to https://www.usajobs.gov
2. Scroll down and click "Students & recent graduates" link (in "Explore hiring paths" section).
3. Scroll down and click "Search recent graduates jobs" link (in "Begin your search" section).
4. End up on https://www.usajobs.gov/Search/Results?wt=15326&hp=graduates, note that the "Recent graduates" filter shows up twice. You have to click both to fully remove the recent graduates filter scope.

**Comment by anselmbradford** [comment]
Note that removing one of them unchecks the "Recent graduates" filter in the sidebar. That doesn't make sense to still have the filter at the top left when the filter in the sidebar is unchecked.

<img width="985" alt="Screen Shot 2022-10-12 at 12 47 48 PM" src="https://user-images.githubusercontent.com/704760/195401850-20ebca5d-1c9a-460c-aea6-7a52fe7fe27b.png">

**Comment by danthibodeau** [comment]
Hello, these are two different filter selections, one for hiring path and one for appointment type (in the More filters area). We will look to make this more clear in the future. You can also use the "Remove all filters" link to easily remove both in the future.

**Comment by anselmbradford** [comment]
> Hello, these are two different filter selections, one for hiring path and one for appointment type (in the More filters area). We will look to make this more clear in the future. You can also use the "Remove all filters" link to easily remove both in the future.

Oh, I see now. So each filter corresponds to the same named filter across the two filter tabs. So the difference is that the hiring path is positions where ONLY graduates can apply and the recent graduates appointment type is positions that are hiring recent graduates among other applicable categories (public, competitive service, etc)? Put another way, the recent graduate hiring path is a subset of the recent graduate appointment type search? It seems like the filter should be something like "limit to only this appointment type" if that's what the filter is doing.

**Comment by danthibodeau** [comment]
Yes, one filter does limit to only that appointment type, while one filter limits to only that hiring path. We will work to make it more clear when filters are named similar/the same.
