### ISSUE TITLE
Session timeout not so friendly

### ISSUE THREAD

**Issue by anselmbradford** [USAJOBS/Help#489]
Hello again! (Please tell me if there's a better place for this)

What is the thinking and requirements behind the session timeout time for usajobs.gov? I have on various occasions opened a bunch of jobs in tabs and then lost them all because I took too much time to go through them. Worse, I have also had the experience of applying to an opportunity on openops.usajobs.gov and filled in my application only to lose all I'd written on hitting "Apply" because I'd been logged out. It seems like maybe there are particular problems when multiple tabs are open (like the session timeout notification arrives and expires in not the tab you're looking at).

**Comment by kbwagner** [comment]
Hello - 

For Open Opportunities issues, you can reach out to openopps@usajobs.gov.  For USAJOBS issues/questions, you can use the contact us feature: https://www.usajobs.gov/Help/Contact

The session timeout feature is a federal government security requirement that we are required to follow.   As long as you are actively typing in one of the systems, you will not get timed out.  But yes, having multiple tabs open can and will cause issues with that.  If you are doing an application, we recommend you save as draft along the way whenever you can.

Hope that helps.  Thanks!

**Comment by anselmbradford** [comment]
Thanks for the response @kbwagner !

> For Open Opportunities issues, you can reach out to [openopps@usajobs.gov](mailto:openopps@usajobs.gov). For USAJOBS issues/questions, you can use the contact us feature: https://www.usajobs.gov/Help/Contact

I was more looking for if there were GitHub repositories associated with the two sites. All I am seeing are specific parts under https://github.com/USAJOBS and not the sites overall. The contact form doesn't allow screenshots, for instance, which can be useful for filing bugs.

**Aside,** I noticed a bug in the contact link 😸. If you visit https://www.usajobs.gov/Help/Contact and click any of the "FAQs", "How To’s", or "Working in Government" links you end up on a not found page. It appears to be because relative paths are being used for the links, so it's expecting a trailing slash on the URL. I.e. https://www.usajobs.gov/Help/Contact/

![usajobs_links](https://user-images.githubusercontent.com/704760/199254072-a6d2d243-c064-43d4-bfd6-97f6dafde82a.gif)

**Comment by kbwagner** [comment]
@anselmbradford we don't use Github at all for ticketing.  The emails/contact us are entered into a ticketing system.  These Github links should actually probably be inactive as most don't have access to them.  

I have forwarded your comment on the contact us to the USAJOBS team.
