### ISSUE TITLE
Help Center Broken Links

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#50]
Several links, in Help Center, need to be fixed.

1. https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/faq/pathways-program-veteran/ - Learn how to upload documents. – Upload documents link provides a 404 error message. Link should go to /Help/how-to/account/documents/upload/

2. https://www.usajobs.gov/Help/how-to/account/documents/resume/build/experience/ - All of the “Related Articles” links on this page are broken. 

3. https://www.usajobs.gov/Help/how-to/search/advanced/profile/ - Additional Resources section, Service link is broken. Should point to: /Help/working-in-government/service/

4. https://www.usajobs.gov/Help/faq/application/eligibility/ - Additional Resource section, Office of Personnel Management: Hiring Authorities link is broken. Should point to https://www.opm.gov/policy-data-oversight/hiring-information/hiring-authorities/

**Comment by humancompanion** [comment]
Item 2 in this list is issue #49 which I won't have a fix for immediately.
