### ISSUE TITLE
Students and Grads broken link

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#52]
Who can make these changes?

https://www.usajobs.gov/StudentsAndGrads/ - Additional information about the Recent Graduates Program link – Goes to broken page, should point to https://www.opm.gov/policy-data-oversight/hiring-information/students-recent-graduates/#url=graduates

Also Internship link should point to https://www.opm.gov/policy-data-oversight/hiring-information/students-recent-graduates/#url=intern

OPM changed their links

**Comment by humancompanion** [comment]
This has to be fixed by Saleim. I just talked to him about it. Dan hopefully will allow him to fix it in the hotfix.
