### ISSUE TITLE
Help Center - Add how to clear cache content

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#57]
The page on how to clear your cache is no longer available. This needs to be added back in.

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

The old content about cache clearing was located here: https://help.usajobs.gov/index.php/How_do_I_clean_out_my_cache_or_my_temporary_internet_files%3F

In the FAQ audit, we had questioned deleting this page..  Is there someplace in the application process that needs to link to this content?  This was not one of the top 50 FAQs, so it didn't get migrated, but we can add it back in if the business thinks it's a need.

Thoughts?

**Comment by PeterToohey** [comment]
@dalenard21 @humancompanion 

Let me chat with Dan about the business need and follow up.  My recommendation would be to put it under FAQs/Troubleshoot

**Comment by humancompanion** [comment]
Why are we suggesting to users that they clear out their cache? What problem are we trying to solve with this FAQ? I recommend we do nothing of the sort. If we have a cache issue we should fix it in code with an expires header adjustment or something of that nature.

**Comment by PeterToohey** [comment]
I just pinged Dan for some context...will let you both know when I hear from him.

**Comment by PeterToohey** [comment]
He is pushing back on Macon for more details.  The helpdesk refers to the content frequently but Dan was unaware that it was outside the Top 50 hits in RC.  More to come

**Comment by dalenard21** [comment]
Confirmed with Dan that we do not need to add the "How to clear my cache" faq back. Issue closed.
