### ISSUE TITLE
External links to old Resource Center (Monday, May 9th)

### ISSUE THREAD

**Issue by dgarber** [USAJOBS/Help#61]
Yesterday we had 3,390 external linkages to the old Resource Center. Some appear direct (i.e., the person entered the url themselves), although I question the validity of many of those. Will need to determine whether it is prudent to attempt to contact the site owners or eventually insert redirects.

[Analytics OPM External Links to Help Center 16-05-09.pdf](https://github.com/USAJOBS/Help/files/257462/Analytics.OPM.Agency.Profile.Pages.20160509-20160509.1.pdf)

**Comment by humancompanion** [comment]
A redirect is now in place from help.usajobs.gov to www.usajobs.gov/Help/
