### ISSUE TITLE
Update who-may-apply pages to include U.S. Citizens and Nationals pages

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#70]
We need to discuss with Dan the changes that are required.

**Comment by dalenard21** [comment]
Per Dan, the language update for who may apply is on hold, while they determine the language.  email, dated 5/13/16 - "This ticket is now on hold while they determine what the language should be. This means it likely won’t go in the June release, unless they want to force it on us when they have it ready so there’s always still the possibility. The ticket is still in a “new” status, but I also just moved it out of the current sprint and put it on the backlog."

**Comment by humancompanion** [comment]
@dalenard21 - While we don't need to update this specific language, we could improve both Who May Apply pages:

http://usajobs.github.io/Help/how-to/search/filters/who-may-apply/
http://usajobs.github.io/Help/how-to/search/advanced/who-may-apply/

The first page in particular will now be linked to from the home page search help icon. Might be an opportunity to direct traffic to:
http://usajobs.github.io/Help/faq/application/eligibility/

As well as:
http://usajobs.github.io/Help/how-to/search/

Thoughts?

**Comment by dalenard21** [comment]
Updated both Who May Apply pages.  Reviewed with Tracy and included her feedback/edits.

We now link to the US citizen and non-citizen pages.

Issue closed.
