### ISSUE TITLE
Update Help Center with Profile Dashboard Changes

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/Help#71]
- [x] How does the application process work **Julie**
- [x] Why was I not considered for a position? **Julie**
- [x] How to change your password **Julie**
- [x] How to delete an account **Julie**
- [x] How to create a profile **Julie**
- [x] How to upload documents **Peter**
- [x] How to check the status of an application **Peter**
- [x] How to continue an application **Peter**
- [x] How to create an application **Peter**
- [x] How to update an application **Debbie**
- [x] How to view a hidden application **Debbie**
- [x] How to save an application **Debbie**
- [x] How to understand the job announcement **Debbie**
- [x] How to save a search **Debbie**
- [x] How to save a job **Debbie**
- [x] How to unsubscribe from a saved search **Debbie**
- [x] How to upload a resume **Debbie**

**Comment by dalenard21** [comment]
@PeterToohey this looks good.  I'll start on the changes.

**Comment by dalenard21** [comment]
@PeterToohey 

Just FYI, we already updated the How to check the status of an application with profile dashboard changes.

**Comment by PeterToohey** [comment]
@dalenard21 Julie is going to help out with updating some How-To's.  Note that the names next to the top 5 have changed.  Julie's git name is @Piglady64

**Comment by humancompanion** [comment]
@PeterToohey & @dalenard21 - You can both go ahead and commit these changes to the main branch (gh-pages). The v5.6 branch has been created and modified appropriately for the v5.6 release. The main branch is now for v5.7 and that's where these changes will go.

**Comment by dalenard21** [comment]
@PeterToohey @humancompanion @Piglady64 

We no longer need how to view a hidden application, because this is covered by how to archive applications.

**Comment by dalenard21** [comment]
Help Center content updates completed. Issue closed.
