### ISSUE TITLE
Create Federal Hiring Myths

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#72]
* [x] You have to know someone to get a federal job.	
  * False: You do NOT need to know someone to get a federal job. If you are qualified for a federal position, you can write a competitive federal resume. Make sure you add the KSAs into the resume and answer the questionnaire giving yourself all the credit that you can. You have to apply correctly following the directions. you CAN get "best qualified" and "referred to a supervisor" without knowing anyone in the government.
* [x] You need a security clearance to qualify for a federal job	
  * False: Not all jobs require a security clearance.You can find this information in the job announcement. 
* [x] A federal resume should not exceed 2 pages.	
  * False: A federal resume requires more information than a civilian resume, therefore, it is typically longer than 2 pages. Some of the things that should be included are your educational and work experience. This includes job titles, salary, employment dates, duties and accomplishments, and how it relates to the knowledge, skills and abilities (KSAs) in the job announcement. 
* [x] You need to tailor your federal resume to each position. 	
  * partially true: Tailoring your resume is not required. However, you must demonstrate in your resume that your are qualified for the position. Remember, this is the only information the Human Resource (HR) Specialist has to determine if your resume should be forwarded to the hiring manager. 
* [x] Resumes are scanned for keywords by an automated system. 	
  * partially true: In most agencies, the resumes are scanned by real people, Human Resource (HR) Specialists. However, NASA uses a contextual grammar based Artificial Intelligence software for an automated resume review. The automated review is more complex than a simple keyword search it is based on a contextual resume content matching. The resume review is used as one step, in a multistep applicant application review process. This process includes a review of all required areas of the applicant’s eligibility and qualifications for the announcement. The resume review portion of the process includes both an automated and manual (by person) review of applicant packages."
* [x] The job announcement looks like it has been written with someone in mind.	
  * False: The job announcement is written by the hiring manager with the assistance of the Human Resource (HR) Specialist. It is written to include the knowledge, skills, and abilities required to perform the duties of the position. 
* [x] I must move to Washington, DC if I want to work for the Federal Government because most federal jobs are in DC.
  * False: About 15% of federal jobs are in the Washington, DC metro area while approximately 83% are found in multiple location s throughout the country and the remaining 2% are outside the United States.

**Comment by humancompanion** [comment]
@dalenard21 - I started creating the federal hiring myths. I've got 2 of 7 in there. I setup the index at /faq/myths/ and added the first two to the FAQ index page. Please add the rest. The text is in the initial comment. After that, assign it back to me and I'll add the rest to the FAQ index page. I appreciate the assist on this one.

**Comment by humancompanion** [comment]
@dalenard21 - One more thing, be sure to name the last one /faq/myths/i-must-move/. I've used that link on the landing page. Thanks.

**Comment by humancompanion** [comment]
@dalenard21 - Scratch that last comment. I had to provide another zip file this morning for a different bug  so I went ahead and created the /faq/myths/i-must-move/ file. Deploying now.

**Comment by dalenard21** [comment]
@humancompanion 

I finished migrating the hiring myths. Feel free to edit the file names or breadcrumbs.  Tried to follow your lead, but a couple are a bit long. Also, at some point I'd like to revisit the language for a few of these.

Assigning back to you.

**Comment by humancompanion** [comment]
@dalenard21 - Thanks. I agree that these need some attention. Specifically, the /faq/myths/job-announcement-written-for-someone/ should mention that such a practice is illegal, the HR manager would likely be disciplined or fired should it happen, and that the Federal hiring practice is by law more fair and balanced than the private sector. This is really an area where OPM should stand up for itself.

But, there is a bigger issue: None of these are phrased as questions yet I put them in FAQs! Should I move the whole sub-section of Myths to Working in Government? Or should we just re-write the titles as questions?

**Comment by humancompanion** [comment]
@dalenard21 - I think the thing to do is more the Myths to Working in Government. Agree? If so, assign to me and I'll take care of it soon.

**Comment by dalenard21** [comment]
Yes, let's move to working in government.

Assign back to @humancompanion
