### ISSUE TITLE
How To/FAQs: Visual Hierarchy

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/Help#76]
Two team members have come to me this week to ask about the intent behind the sub-heading sizes on the How To and FAQ landing pages.  People do not understand that Profile and Document are subsections of account and that Resumes are a subsection of documents.

I will review this page and determine if any changes need to be made.

**Comment by PeterToohey** [comment]
@humancompanion It appears that the intent behind using H3, H4 and H5 on the How To and FAQ sections was to reflect the IA. For example, Documents is H4 and Resumes (a subset of documents) is H5.   I don't think the intent behind the design is coming through accurately to users causing confusion as to why sub-section headings are different sizes.  Based on a brief competitive analysis, other websites either do not try to visually indicate sub-sections or do it with a combination of visual cues (font size, indentation or color).  

My recommendation would be to have all How To and FAQ sections being H3s.  

Also - we need to update "Job announcement" H3 on FAQs page to be "Job Announcement"

Let me know your thoughts.

**Comment by humancompanion** [comment]
Designs from Min are here: https://projects.invisionapp.com/d/#/projects/8330539

Implementing these now.

**Comment by humancompanion** [comment]
@minchung12 & @dalenard21 - Let's talk about the organization of the sub-sections. I want to be sure I got that right.

More importantly, let's talk to @nourax and see if there is the possibility of updating the link from the landing page to the appropriate myth in 5.8 before we move the myths from working in government to FAQs. I didn't make this change. I believe it is too late and we should wait to move them for when we next update the myth on the landing page. But, it doesn't hurt to ask. Regardless, I'll file a new github issue for that change.
