### ISSUE TITLE
Generate v5.6 release

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#77]
Since we've decided to release v5.6 without the Profile Dashboard feature we need to revert content that mentions it back to the v5.5 release version. There have been 51 commits since then. Rather than cherry pick those commits, which have a mix of things we do, and do not, want, I am going to create a list of files that need to be reverted and revert those on a branch.

**Comment by humancompanion** [comment]
* [ ] how-to/application/status.md revert to 4b8603b2f4cda8871bc122dfe6674fe46a55548f
* [ ] how-to/job-announcement/save.md - Remove (no prior version)
* [ ] how-to/account/documents/index.md - Edit the initial steps - valuable content that needs a simple change to remain accurate
* [ ] how-to/search/save/index.md revert to e662697f32955e1af51cc0bec2ef0c0f585789c6

**Comment by humancompanion** [comment]
Hopefully I did this correctly and it is here:
https://github.com/USAJOBS/Help/releases/tag/v5.6.7

**Comment by dalenard21** [comment]
@humancompanion 

I found two other pages that I edited:

 /how-to/application/archive.md - this one needs to be pulled or reverted back

 /Help/faq/application/documents/resume/what-to-leave-out/ - I don't think this is profile dashboard specific. It expands on the content of what someone shouldn't include in their resume.  I think it's okay to keep as is and not revert back, but please review.

Thanks.

**Comment by humancompanion** [comment]
New tag:
https://github.com/USAJOBS/Help/releases/tag/v5.6.8
