### ISSUE TITLE
Help Icon in Filter is not anchoring to 'How to Filter Applications'

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/Help#78]
All - 

The help icon in the Application Status Filter drawer is not anchoring the the "How to Filter Applications" section of the "How to check on the status of an application" page.  Does this need to be coded by Macon or can we do this on our side?

It is not working in the prototype.

Peter

**Comment by dalenard21** [comment]
@PeterToohey @humancompanion @nourax 

I think I fixed the anchor link in the page itself.  At least it's working in the preview of github.

Noura,  

Use this URL for the help icon: Help/how-to/application/status/#how-to-filter-applications

**Comment by dalenard21** [comment]
@PeterToohey , @nourax 

I just checked the prototype and it looks like the help link is now anchoring to the correct link location.  Can you please review and confirm?  If so, we can close the issue.

**Comment by PeterToohey** [comment]
@dalenard21 @nourax Confirmed.  It is anchoring properly in the prototype.  Thx - Debbie.

**Comment by dalenard21** [comment]
Closing issue.
