### ISSUE TITLE
Create new unique hiring path pages

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#84]
* [x] Individual with a disability
* [x] Veterans
* [x] Federal Employees
* [x] Students & Recent Graduates
* [x] Senior Executives
* [x] Military Spouses
* [x] Former Overseas employees
* [x] Peace Corps & VISTA alumni

### Follow-up tasks

* [x] FedsHireVets logo and top section
* [x] Pathways logo
* [x] Search component for SES & Students
* [x] Make all page titles consistent
* [x] Make the accordions function
* [x] Handle Military Spouse logo (2 icons)

**Comment by humancompanion** [comment]
@kyhryt - I need the images for Military Spouses as well as the logo images you used for FedsHireVets and Pathways. Thanks.

**Comment by humancompanion** [comment]
@kyhryt - The FedsHireVets logo image you supplied does not have a transparent background like it does in your mock-up. Can you either provide an image with a transparent background or give me a design that works with their gray background? Thanks.

**Comment by kyhryt** [comment]
@humancompanion try this. The BG color is #d8eaef

<img width="143" alt="feds-hire-vets-logo-blue-bg" src="https://cloud.githubusercontent.com/assets/15234468/16878353/38bd5b5c-4a7a-11e6-8972-a7d0d6bbee49.png">

**Comment by humancompanion** [comment]
Close! The background color should be #e1f3f8.

**Comment by kyhryt** [comment]
@humancompanion I have two requests. 

1. Is it possible to reduce the width of the content to be two thirds: https://standards.usa.gov/grids/. The line length is too wide. This makes it difficult for readers to focus on the text. 

2. Add a border around the shell, like we did in dashboard. This is not ideal, but the content is floating in space. 

Thanks,
Ky.
