### ISSUE TITLE
UHP: Review capitalization

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#85]
Moved from https://github.com/USAJOBS/american-discovery-trail/issues/81

Go through the unique hiring path pages to review use of capitalization and consistency.

@dalenard21 - I believe I'm following the rules you outlined here https://github.com/USAJOBS/american-discovery-trail/wiki/Capitalization excluding the h1s of these pages which are in the hero and remain title case. But, please review my work and ensure I've done what you outlined consistently. Thanks.

**Comment by dalenard21** [comment]
@humancompanion 

**Federal employees**

looks good

**Students and recent graduates**

1. Let's capitalize "internship program" in the first sentence of the Internship Program paragraph and also in the "Learn more" link.
2. Do not capitalize the word "List" in the additional resources link "A-Z List..."
3. Nothing to do with capitalization, but the expand and collapse feature of the different program information is not working

**Military spouse**

1. The Additional resource link needs to use sentence case.

**Veterans**

1. I think it looks good. I want to confirm that we should treat those hiring paths as pronouns. I'm guessing yes, so let's leave it as you have it now (the links to the other hiring paths).
2. I'd like to update the 'Tutorial (FedsHireVets)" link label - I'll look at the tutorial and see if there's a better label to use.

**Senior executives**

1. Under Additional resources, "Senior Executive Service pay table".  I don't think pay table needs to be capitalized.
2. Let's change the "Senior Executive Service FAQs" to just say "Frequently asked questions" to be consistent with the other unique hiring path pages

Individuals with a disability

1. Under Eligibility, I don't think we need to capitalize "Tips for Applying under Schedule A.".  Let's change it to "Tips for applying under Schedule A"

Peace Corp and AmericCorp VISTA

1. Last paragraph, looks like the "Learn more" link isn't linked.
2. Everything else looks good.
