### ISSUE TITLE
UHP: Add DOD only language to Military Spouse page

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#86]
The Military Spouse page needs to mention that this eligibility is only extended by the Department of Defense and the jobs they post.

**Comment by dalenard21** [comment]
@Piglady64 

If you're updating this page, what about including this in:

**Hero copy**

If you're a military spouse, you may be eligible to apply and be hired for competitive service jobs with the Department of Defense, without having to go through the entire application process.

**First paragraph**

Supported by Executive Order 13473, the Department of Defense can use this hiring path to fill competitive service positions on either a temporary or permanent basis.

or something like that.

**Comment by Piglady64** [comment]
Debbie,
  I found out on Tuesday when I was at the Hiring Excellence event at USDA that there is also a federal government wide program for military spouses. That is why I need to talk to this SME.  I had sent Peter two texts during the day to let him know, I guess he didn’t relay the message.

Julie Jackson

Office of Personnel Management
USAJOBS PMO
ES IT PMO
Phone : 202-606-5230
Julie.jackson@opm.gov

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

@Piglady64 provided some great feedback on the military spouse page.  The military spouse hiring option is not just for DOD.  Any federal agency can use it.  

I've attached updated content to clarify this hiring path - Julie has reviewed and it includes her feedback.  

@humancompanion can you update the page with this content?
[military-spouses-hiring-path_20160801_v03.docx](https://github.com/USAJOBS/Help/files/394665/military-spouses-hiring-path_20160801_v03.docx)
