### ISSUE TITLE
FAQs: Revise federal application process content

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/Help#88]
Update the content on https://www.usajobs.gov/Help/faq/application/process/ to incorporate feedback from the usability test.  Ensure the content is inline with the federal application process content on the landing page.

**Comment by humancompanion** [comment]
@dalenard21 - I'll talk to Michelle about this next week, perhaps I'll even raise it in the PO meeting just to get a sense of how wide the scope of this page should go.

**Comment by dalenard21** [comment]
Provided content to Tracy - waiting to get feedback.

**Comment by humancompanion** [comment]
@dalenard21 - Have you already updated this in github? Do I need to make any edits? If I do please attach or inline an updated doc. Thanks!

**Comment by dalenard21** [comment]
Nope, haven't updated yet, because I'm waiting for feedback from Tracy.  I'll follow up with her again.

**Comment by dalenard21** [comment]
Received feedback and edits from Tracy.    Content updates made.  Issue closed.
