### ISSUE TITLE
5.7 Help Center Testing

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/Help#96]
The amount of content being migrated to the Help Center is increasing so we need a more sound testing strategy.  For 5.7 (during the bug bash and post production deployment) this checklist will be used to ensure that the files have been uploaded correctly to Test and Prod:

- [x] **How does the application process work** - Validate that the term 'Profile Dashboard' has been scrubbed from the content.
- [x] **Why was I not considered for a position?** - Validate that reference to "My Account" have been removed.
- [x] **How to change your password** - Validate that the new steps refer to "Username & Password" not Profile or Account Information tab
- [x] **How to delete an account** - Ensure references to Profile and My Account were removed.
- [x] **How to create a profile** - Ensure the steps to create a profile to match the revised sections in profile dashboard.
- [x] **How to upload documents** - Ensure references to My Account have been removed. Check that new steps added that match how to upload in new profile dashboard

- [x] **How to make your resume searchable** - Ensure that content states your resume will remain searchable for 18 months instead of 16 months
- [x] **How to check on the status of an application** - Ensure that the content reflects that the language and steps reflect the new profile dashboard setup.
- [x] **How to continue an application** - Ensure "log in" has been changed to Sign into, all references to My Account have been removed and steps to match the new profile dashboard.
- [x] **How to create an application** - Ensure "log in" has been changed to Sign into, all references to My Account have been removed and steps to create an account match the new profile dashboard.
- [x] **How to update an application** - Ensure "log in" has been changed to Sign into, all references to My Account have been removed and steps to create an account match the new profile dashboard.
- [x] **How to view a hidden application** - Ensure content has been revoked.
- [x] **How to save an application** - Ensure that the steps to save an application match the new profile dashboard
- [x] **How to understand the job announcement** - Ensure that the content is edited to incorporate different headings and cleaned up content. 
- [x] **How to save a search** - Ensure that "Log in" has been changed to Sign in, all references to My Account have been removed, and new steps match new profile dashboard. Check that more content has been added about managing a saved search.
- [x] **How to unsubscribe from a saved search** - Ensure references to My Account have been removed, and that new steps have been added to match how to unsubscribe in the new profile dashboard.
- [x] **How to upload a resume** - Ensure references to My Account have been removed and steps to upload resume are added to the new profile dashboard document section.
- [x] **What should I leave out of my resume** - Ensure content is edited to provide more details.
- [x] **How to archive a job application** - Ensure that steps to archive a job application are included in the new profile dashboard.
- [x] **How to view applications** - Ensure that steps to view job applications are included in the new profile dashboard.
- [x] **How to make your resume searchable** - Ensure that content is edited to include additional details and steps in the new profile dashboard.
- [x] **How to edit a resume** - Ensure that steps for how to edit a resume are edited and links in the Additional Information section are updated to include the federal resume pdf.
- [x] **How to build a resume** -  Ensure that "Log in" has been changed to Sign in and new steps match new profile dashboard. 
- [x] **How to print a resume** - Ensure that more detailed steps for how to print are added.
- [x] **What should I include in my resume** - Ensure content is updated to include content from RPO, and links are added to the video in additional information.
- [x] **How to answer questions about federal employment**  - Ensure that this is linked to from the profile dashboard.
- [x] **How to answer questions about military service** - Ensure that this is linked to from the profile dashboard.
- [x] **How to filter by who may apply** - Ensure that this is updated to include language about Nationals and individuals who owe allegiance to the U.S. and more details are added around Federal Employees, including military spouses, former overseas employees, individuals with a disability, Peace Corps, or AmeriCorps VISTA Alumni.

**Comment by humancompanion** [comment]
I've confirmed the first two using ack (http://beyondgrep.com/). I also confirmed there are no references to "My Account". However, there is one instance of "my account" in how-to/job-announcement/save/ that is okay ("What if I don't see a saved job in my account?").

There are two instances of "log in" that I found in /how-to/account/password/reset/ and /how-to/application/view/ which I just fixed. The remaining 5 will have to be verified manually.

**Comment by dalenard21** [comment]
**How to understand the job announcement**

- [ ] Add more info in the qualifications section - consider linking to what to include in a resume?  or at least add content that suggests you must include qualifications in your resume

**How to change your password**

- [ ] Remove bold from "button" in "Save button"
- [ ] Add periods to bulleted list

**How to delete an account**

- [ ] Add lead in sentence under additional information "If you delete your account:"

**How to make your resume searchable**

- [ ] Update 16 to 18 - looks like this was done in github, but need to include the updated file in the next help center push

**Comment by dalenard21** [comment]
issue closed.
