### ISSUE TITLE
Move Myths from Working in Government to FAQs

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#97]
@minchung12 suggested in her Help Center layout design that myths should move to FAQs. Not sure if that decision came from @dalenard21 or not though I know we've discussed it in the past. This issue tracks the work to:

* [ ] Move the files physically on the filesystem and update their titles
* [ ] Update the wording of the myths to be in the form of a question (they are not currently)
* [ ] File a TFS ticket to change the link on the landing page and/or rotate in a new myth there.

**Comment by dalenard21** [comment]
@humancompanion @minchung12 

We originally had the myths in the FAQ section, but they were never written as an FAQ.  Then @humancompanion suggested they go to working in government, and that's when they moved there. I think they could live in either place, but if they go into FAQ we have to rewrite them.   It really depends how we want to phrase them.  Do people ask these as questions or do we want to present them as a statement?

@minchung12 can you give me access to the invision file?  I signed in, but don't have access.  Username is dalenard21@gmail.com.

**Comment by minchung12** [comment]
@humancompanion @dalenard21 
I actually grabbed the content from the live site so that's why I have Myths under FAQs, but I think it should live under Working in Government and present them as a statement. 

@dalenard21 I sent out an invitation to access the file, please let me know if it doesn't work.

**Comment by humancompanion** [comment]
@minchung12 - Yea, I moved them to working in government. So closing this as there is nothing more to do.
